
// Layer groups — compound parent nodes (visual grouping)
const layers = [
  { id: 'L_GCP',      label: '☁️ Google Cloud Platform',  v: ['cortex'], desc: 'Wszystkie crony + backupy + monitoring. Project: ai-council-487609. Koszt ~10-12 zł/mies.' },
  { id: 'L_MIKRUS',   label: '🐧 Mikrus VPS',              v: ['cortex'], desc: 'Persistent WA sesje + on-host pg_dump. leszek140, 20 zł/mies.' },
  { id: 'L_LAPTOP',   label: '💻 Laptop (penguin)',        v: ['cortex'], desc: 'Praca interaktywna. Cortex runtime. ZERO cronów produkcyjnych.' },
  { id: 'L_VERCEL',   label: '▲ Vercel',                  v: ['cortex'], desc: 'Apki frontend/backend Next.js.' },
  { id: 'L_DHOSTING', label: '🌐 Dhosting',                v: ['cortex'], desc: 'Statyczne strony WWW. Crony PHP zablokowane.' },
];

// Node → Layer mapping (ktory node do ktorej warstwy)
const nodeToLayer = {
  // GCP
  gcp: 'L_GCP', gcp_sm: 'L_GCP', gcp_bucket: 'L_GCP', gcp_ar: 'L_GCP', gcp_uptime: 'L_GCP',
  cr_notion_backup: 'L_GCP', cr_supabase_backup: 'L_GCP', cr_cloudflare_backup: 'L_GCP',
  cr_recenzent: 'L_GCP', cr_content: 'L_GCP',
  sch_notion: 'L_GCP', sch_supabase: 'L_GCP', sch_cf: 'L_GCP', sch_recenzent: 'L_GCP',
  sch_content: 'L_GCP', sch_pm_scan: 'L_GCP', sch_pm_summary: 'L_GCP', sch_pm_retry: 'L_GCP',
  // Mikrus
  mikrus: 'L_MIKRUS', app_janusz: 'L_MIKRUS', app_gustaw: 'L_MIKRUS',
  mikrus_pg: 'L_MIKRUS', cron_archiwista: 'L_MIKRUS', archiwista_sh: 'L_MIKRUS', strych: 'L_MIKRUS',
  // Laptop
  laptop: 'L_LAPTOP', timer_context: 'L_LAPTOP', timer_smoke: 'L_LAPTOP',
  timer_seo: 'L_LAPTOP', timer_claude_backup: 'L_LAPTOP', env_file: 'L_LAPTOP',
  repo_cortex: 'L_LAPTOP', claude_md: 'L_LAPTOP', context_md: 'L_LAPTOP',
  knowledge_dir: 'L_LAPTOP', venv: 'L_LAPTOP',
  notion_map: 'L_LAPTOP', ecosystem_map: 'L_LAPTOP', apps_map: 'L_LAPTOP',
  quotes_mazur: 'L_LAPTOP', adi_psychology: 'L_LAPTOP',
  app_atlas: 'L_LAPTOP',
  // Vercel
  vercel: 'L_VERCEL', app_pm: 'L_VERCEL', app_zakupex: 'L_VERCEL',
  app_bot_voice: 'L_VERCEL', app_muszla: 'L_VERCEL',
  // Dhosting
  dhosting: 'L_DHOSTING',
};

// v = views this node belongs to
const nodes = [
  // ========== CORTEX VIEW ==========
  // Core files
  { id: 'claude_md',         label: 'CLAUDE.md',             type: 'core',   v: ['cortex'], desc: 'Główne instrukcje Cortexu — tryby, formaty, trigger phrases, harmonogram briefingów' },
  { id: 'context_md',        label: 'context.md',            type: 'core',   v: ['cortex'], desc: 'Kontekst dnia — generowany o 07:00. Kalendarz (PEG+prywatny+rodzinny), zadania, CRM, habits, inbox (2 konta)' },
  { id: 'env_file',          label: '.env',                  type: 'core',   v: ['cortex'], desc: 'Tokeny i klucze API — Notion (2x), Gmail, Cloudflare, OpenAI, Google Ads, Fireflies' },
  { id: 'knowledge_dir',     label: 'knowledge/',            type: 'core',   v: ['cortex'], desc: 'Baza wiedzy: agents/, maps/, www/, apps/' },
  { id: 'quotes_mazur',      label: 'quotes_mazur.md',       type: 'core',   v: ['cortex'], desc: 'Cytaty Mazura — konfrontacja, mobilizacja, kotwica' },
  { id: 'adi_psychology',    label: 'adi_psychology.md',      type: 'core',   v: ['cortex'], desc: 'Profil psychologiczny — reset, triage, strategia' },
  { id: 'notion_map',        label: 'notion_map.md',         type: 'core',   v: ['cortex'], desc: 'Mapa 32 baz Notion — ID, relacje, statusy' },
  { id: 'ecosystem_map',     label: 'ecosystem_map.md',      type: 'core',   v: ['cortex'], desc: 'Pełna mapa ekosystemu PEG' },
  { id: 'apps_map',          label: 'apps_map.md',           type: 'core',   v: ['cortex'], desc: 'Mapa aplikacji ~/APP' },
  { id: 'venv',              label: 'scripts/venv/',         type: 'core',   v: ['cortex'], desc: 'Python virtualenv' },

  // Scripts
  { id: 'gmail_py',          label: 'gmail.py',              type: 'script', v: ['cortex'], desc: 'list, read, send, draft, search [--private]' },
  { id: 'calendar_py',       label: 'google_calendar.py',    type: 'script', v: ['cortex'], desc: 'list, add, delete, rsvp, calendars [--private]' },
  { id: 'notion_py',         label: 'notion.py',             type: 'script', v: ['cortex'], desc: 'query, search, add-task, add-note, add-activity' },
  { id: 'notion2email_py',   label: 'notion_to_email.py',    type: 'script', v: ['cortex'], desc: 'Notion page -> HTML email' },
  { id: 'cloudflare_py',     label: 'cloudflare.py',         type: 'script', v: ['cortex'], desc: 'overview, detail, cache, purge' },
  { id: 'seo_report_py',     label: 'seo_report.py',         type: 'script', v: ['cortex'], desc: 'raport SEO -> Notion' },
  { id: 'health_check_py',   label: 'health_check.py',       type: 'script', v: ['cortex'], desc: 'smoke test integracji' },
  { id: 'fireflies_py',      label: 'fireflies_to_notion.py',type: 'script', v: ['cortex'], desc: 'transkrypcje -> Notion' },
  { id: 'google_ads_py',     label: 'google_ads.py',         type: 'script', v: ['cortex'], desc: '19 komend: kampanie, KP, forecast' },
  { id: 'ga4_py',            label: 'ga4.py',                type: 'script', v: ['cortex'], desc: 'dane GA4' },
  { id: 'search_console_py', label: 'search_console.py',     type: 'script', v: ['cortex'], desc: 'pozycje, kliki GSC' },
  { id: 'deploy_ftp_sh',     label: 'deploy_ftp.sh',         type: 'script', v: ['cortex'], desc: 'deploy FTP stron' },
  { id: 'update_context_py', label: 'update_context.py',     type: 'script', v: ['cortex'], desc: 'generuje context.md' },
  { id: 'smoke_test_py',     label: 'smoke_test.py',         type: 'script', v: ['cortex'], desc: 'test Notion + Gmail' },
  { id: 'google_admin_py',  label: 'google_admin.py',       type: 'script', v: ['cortex'], desc: 'users, groups, aliases, security, report — Google Workspace' },
  { id: 'indexing_py',      label: 'indexing.py',           type: 'script', v: ['cortex'], desc: 'submit, inspect, sitemap — Google Indexing API' },
  { id: 'check_treningi_py',label: 'check_treningi.py',     type: 'script', v: ['cortex'], desc: 'podsumowanie treningów z Notion' },
  { id: 'notion_replace_py',label: 'notion_replace_page.py',type: 'script', v: ['cortex'], desc: 'kasuje i odtwarza strone Notion (masowa edycja)' },
  { id: 'update_supl_py',   label: 'update_suplementy.py',  type: 'script', v: ['cortex'], desc: 'aktualizacja bazy suplementów' },

  // Timers
  { id: 'timer_context',   label: 'cortex-context (07:00)',type: 'timer', v: ['cortex'], desc: 'systemd -> update_context.py' },
  { id: 'timer_smoke',     label: 'cortex-smoke (07:10)',  type: 'timer', v: ['cortex'], desc: 'systemd -> smoke_test.py' },
  { id: 'timer_seo',       label: 'cortex-seo (pon 07:15)',type: 'timer', v: ['cortex'], desc: 'systemd -> seo_report.py' },
  { id: 'timer_claude_backup', label: 'cortex-claude-backup (22:00)', type: 'timer', v: ['cortex'], desc: 'systemd -> claude_config_backup.py --gcs (fallback po EOD)' },

  // APIs
  { id: 'gmail_api',       label: 'Gmail API',             type: 'api', v: ['cortex'], desc: 'OAuth, email ops' },
  { id: 'calendar_api',    label: 'Google Calendar API',   type: 'api', v: ['cortex'], desc: 'OAuth, events' },
  { id: 'notion_api_firm', label: 'Notion API (firmowe)',   type: 'api', v: ['cortex'], desc: 'NOTION_TOKEN_FIRMOWE, 20 baz' },
  { id: 'notion_api_priv', label: 'Notion API (prywatne)', type: 'api', v: ['cortex'], desc: 'NOTION_TOKEN_PRYWATNE, 12 baz' },
  { id: 'cloudflare_api',  label: 'Cloudflare API',        type: 'api', v: ['cortex'], desc: 'cache, purge, analytics' },
  { id: 'openai_api',      label: 'OpenAI API',            type: 'api', v: ['cortex'], desc: 'GPT-4o, Whisper' },
  { id: 'fireflies_api',   label: 'Fireflies API',         type: 'api', v: ['cortex'], desc: 'transkrypcje spotkań' },
  { id: 'google_ads_api',  label: 'Google Ads API',        type: 'api', v: ['cortex'], desc: 'Basic Access, MCC' },
  { id: 'ga4_api',         label: 'GA4 API',               type: 'api', v: ['cortex'], desc: 'analytics 4' },
  { id: 'gsc_api',         label: 'Search Console API',    type: 'api', v: ['cortex'], desc: 'pozycje, kliki' },
  { id: 'psi_api',         label: 'PageSpeed Insights',    type: 'api', v: ['cortex'], desc: 'GOOGLE_API_KEY' },
  { id: 'gdrive_api',      label: 'Google Drive API',      type: 'api', v: ['cortex'], desc: 'OAuth, backup' },
  { id: 'dhosting_ftp',    label: 'dhosting FTP',          type: 'api', v: ['cortex'], desc: 'FTP deploy' },
  { id: 'supabase',        label: 'Supabase',              type: 'api', v: ['cortex'], desc: 'DB: PM, ZakupEX' },
  { id: 'apify',           label: 'Apify',                 type: 'api', v: ['cortex'], desc: 'scraping cen, Otodom' },
  { id: 'google_admin_api',label: 'Google Admin SDK',      type: 'api', v: ['cortex'], desc: 'users, groups, aliases — Workspace PEG' },
  { id: 'indexing_api',    label: 'Google Indexing API',   type: 'api', v: ['cortex'], desc: 'submit URLi do Google' },
  { id: 'mikrus_pg',       label: 'PostgreSQL (Mikrus)',   type: 'api', v: ['cortex'], desc: 'DB Janusz: messages_log, timecard_entries' },

  // MCP
  { id: 'mcp_chrome',      label: 'claude-in-chrome',      type: 'mcp', v: ['cortex'], desc: 'automatyzacja Chrome' },
  { id: 'mcp_canva',       label: 'Canva MCP',             type: 'mcp', v: ['cortex'], desc: 'tworzenie designów' },
  { id: 'mcp_notion_ai',   label: 'Notion (claude.ai)',    type: 'mcp', v: ['cortex'], desc: 'Notion z Claude.ai' },
  { id: 'mcp_notion_firm', label: 'notion-firmowe MCP',    type: 'mcp', v: ['cortex'], desc: 'API bazy firmowe' },
  { id: 'mcp_notion_priv', label: 'notion-prywatne MCP',   type: 'mcp', v: ['cortex'], desc: 'API bazy prywatne' },
  { id: 'mcp_fireflies',   label: 'Fireflies MCP',         type: 'mcp', v: ['cortex'], desc: 'transkrypcje' },
  { id: 'mcp_gmail',       label: 'Gmail MCP',             type: 'mcp', v: ['cortex'], desc: 'Gmail z Claude.ai' },
  { id: 'mcp_calendar',    label: 'Calendar MCP',          type: 'mcp', v: ['cortex'], desc: 'kalendarz z Claude.ai' },

  // Apps
  { id: 'app_pm',          label: 'PM',                    type: 'app', v: ['cortex'], desc: 'Pricing Manager — Next.js 16, Supabase, Apify — price.partnerexpert.work' },
  { id: 'app_zakupex',     label: 'ZakupEX',               type: 'app', v: ['cortex'], desc: 'System faktur — Next.js 16, Supabase, OCR GPT-4o — zakupex.vercel.app' },
  { id: 'app_janusz',      label: 'Janusz',                type: 'app', v: ['cortex'], desc: 'PERSONA: WhatsApp bot zespołu PEG + PM obowiązki — Node.js, Baileys, GPT-4o-mini — Mikrus (🟢 live)' },
  { id: 'app_gustaw',      label: 'Gustaw',                type: 'app', v: ['cortex'], desc: 'PERSONA: WhatsApp asystent Adiego — Node.js, Baileys, GPT-4o + Gemini — Mikrus (🔴 czeka na SIM)' },
  { id: 'app_bot_voice',   label: 'BOT Voice',             type: 'app', v: ['cortex'], desc: 'Voice -> Notion — Next.js 14, Whisper, Vercel' },
  { id: 'app_atlas',       label: 'Atlas',                 type: 'app', v: ['cortex'], desc: 'Interaktywna mapa ekosystemu PEG (Cytoscape.js)' },
  { id: 'app_muszla',      label: 'muszla.pl',             type: 'app', v: ['cortex','biznesy'], desc: 'muszlakolobrzeg.pl — Astro 5, React 19, Tailwind 4, Vercel' },

  // Nowe skrypty (2026-04-11)
  { id: 'gbp_py',             label: 'gbp.py',               type: 'script', v: ['cortex'], desc: 'Google Business Profile — list, open, close, hours, reviews, reply. Aliasy: muszla, indu, sunday...' },
  { id: 'content_pipeline_py',label: 'content_pipeline.py',  type: 'script', v: ['cortex'], desc: 'Rolki + posty z podcastu Tamborskiego — Whisper, GPT-4o, ffmpeg, OpenCV. Zmigrowane na GCP Cloud Run Job 2026-04-12.' },
  { id: 'archiwista_sh',     label: 'archiwista.sh',        type: 'script', v: ['cortex'], desc: 'Backup PG + .env → strych.mikr.us + GCS' },

  // Automaty Mikrusa (tylko archiwista pozostal, reszta na GCP od 2026-04-12)
  { id: 'cron_archiwista',   label: 'archiwista (4:00)',     type: 'automat', v: ['cortex'], desc: '🟢 Backup PG + .env → strych.mikr.us + GCS, codziennie 4:00, retencja 30 dni. JEDYNY cron na Mikrusie.' },

  // Nowe API
  { id: 'gbp_api',           label: 'GBP API',               type: 'api', v: ['cortex'], desc: 'Google Business Profile — wizytówki, recenzje, godziny' },
  { id: 'fb_api',            label: 'Facebook API',           type: 'api', v: ['cortex'], desc: 'Page token Tamborski — auto-publish postów i rolek' },
  { id: 'strych',            label: 'strych.mikr.us',        type: 'hosting', v: ['cortex'], desc: 'Serwer backupowy Mikrusa — 683GB, SSH/SCP, darmowy' },

  // Repos
  { id: 'repo_cortex',     label: 'Cortex.git',            type: 'repo', v: ['cortex'], desc: 'System operacyjny AI — ~/Cortex + /home/cortex/ na Mikrusie' },
  { id: 'repo_pm',         label: 'PM.git',                type: 'repo', v: ['cortex'], desc: 'Next.js, Supabase' },
  { id: 'repo_zakupex',    label: 'Zakupex.git',           type: 'repo', v: ['cortex'], desc: 'Next.js, Supabase' },
  { id: 'repo_janusz',     label: 'Janusz.git',            type: 'repo', v: ['cortex'], desc: 'Node.js, Baileys, PostgreSQL' },
  { id: 'repo_gustaw',     label: 'Gustaw.git',            type: 'repo', v: ['cortex'], desc: 'Node.js, Baileys, GPT-4o — WhatsApp asystent Adiego' },
  { id: 'repo_muszla',     label: 'muszla.pl.git',         type: 'repo', v: ['cortex'], desc: 'Astro' },
  { id: 'repo_voice',      label: 'voice-notion-app.git',  type: 'repo', v: ['cortex'], desc: 'Node.js' },

  // Hosting
  { id: 'vercel',          label: 'Vercel',                type: 'hosting', v: ['cortex'], desc: 'PM, ZakupEX, BOT Voice, muszla.pl' },
  { id: 'dhosting',        label: 'dhosting',              type: 'hosting', v: ['cortex'], desc: 'FTP: IND.U, Sunday, PEG, GEA. Crony PHP ZABLOKOWANE 2026-04-12 (migrowane na GCP Scheduler).' },
  { id: 'gcp',             label: 'GCP Cortex',            type: 'gcp', v: ['cortex'], desc: 'Project ai-council-487609, region europe-central2. Budget 50zł/mies (alerty 50/90/100%). Realny koszt ~10-12zł.' },
  { id: 'gcp_sm',          label: 'Secret Manager',        type: 'secret', v: ['cortex'], desc: '8 sekretów: notion-token-firmowe/prywatne, supabase-pm-key, supabase-zakupex-key, openai-api-key, cloudflare-api-token, cortex-api-key, google-oauth-token' },
  { id: 'gcp_bucket',      label: 'gs://peg-backups-cortex', type: 'bucket', v: ['cortex'], desc: 'Bucket GCS, lifecycle 30 dni. Foldery: notion/, supabase/, cloudflare/, claude-config/, mikrus/' },
  { id: 'gcp_ar',          label: 'Artifact Registry',     type: 'gcp', v: ['cortex'], desc: 'cortex-jobs/ — Docker images dla Cloud Run Jobs' },
  { id: 'gcp_uptime',      label: 'Uptime Check + Alert',  type: 'gcp', v: ['cortex'], desc: 'janusz-mikrus-health co 5min → /health. Alert email: Janusz DOWN po 60s.' },

  // GCP Cloud Run Functions (4)
  { id: 'cr_notion_backup', label: 'notion-backup',        type: 'gcp', v: ['cortex'], desc: 'Cloud Run Function — 28 baz Notion → GCS' },
  { id: 'cr_supabase_backup', label: 'supabase-backup',    type: 'gcp', v: ['cortex'], desc: 'Cloud Run Function — PM + ZakupEX → GCS' },
  { id: 'cr_cloudflare_backup', label: 'cloudflare-backup',type: 'gcp', v: ['cortex'], desc: 'Cloud Run Function — 6 zon CF → GCS' },
  { id: 'cr_recenzent',    label: 'recenzent',             type: 'gcp', v: ['cortex'], desc: 'Cloud Run Function — Auto-odpowiedzi na recenzje GBP (5 obiektow PEG). GPT-4o-mini.' },

  // GCP Cloud Run Job
  { id: 'cr_content',      label: 'content-pipeline',      type: 'gcp', v: ['cortex'], desc: 'Cloud Run Job (Docker+ffmpeg+yt-dlp+opencv) — rolki podcast Tamborskiego' },

  // GCP Schedulers (8)
  { id: 'sch_notion',      label: 'notion-backup (4:00)',  type: 'sched', v: ['cortex'], desc: 'codziennie 4:00 → CR notion-backup' },
  { id: 'sch_supabase',    label: 'supabase-backup (4:30)',type: 'sched', v: ['cortex'], desc: 'codziennie 4:30 → CR supabase-backup' },
  { id: 'sch_cf',          label: 'cloudflare-backup (5:00)',type: 'sched', v: ['cortex'], desc: 'codziennie 5:00 → CR cloudflare-backup' },
  { id: 'sch_recenzent',   label: 'recenzent (co 4h)',     type: 'sched', v: ['cortex'], desc: 'co 4h → CR recenzent' },
  { id: 'sch_content',     label: 'content-pipeline (wt 3:00)',type: 'sched', v: ['cortex'], desc: 'wtorek 3:00 → CR Job content-pipeline' },
  { id: 'sch_pm_scan',     label: 'pm-auto-scan (23:00)',  type: 'sched', v: ['cortex'], desc: 'codziennie 23:00 → GET price.partnerexpert.work/api/cron/auto-scan' },
  { id: 'sch_pm_summary',  label: 'pm-summary (01:00)',    type: 'sched', v: ['cortex'], desc: 'codziennie 01:00 → GET .../generate-summary' },
  { id: 'sch_pm_retry',    label: 'pm-retry (06:00)',      type: 'sched', v: ['cortex'], desc: 'codziennie 06:00 → GET .../retry-apify-runs' },
  { id: 'mikrus',          label: 'Mikrus VPS',            type: 'hosting', v: ['cortex'], desc: 'leszek140, 1GB/10GB — Persony: Janusz (🟢), Gustaw (🔴). Jedyny automat: archiwista (4:00). Wszystkie inne crony migrowane na GCP 2026-04-12.' },
  { id: 'laptop',          label: 'Laptop (penguin)',       type: 'hosting', v: ['cortex'], desc: 'systemd timers, Cortex runtime — NIGDY crony produkcyjne' },

  // ========== BIZNESY VIEW ==========
  // Holding
  { id: 'biz_peg',     label: 'PEG',                type: 'holding',   v: ['biznesy','zespol'], desc: 'Partner Expert GROUP — holding' },
  // Spolki
  { id: 'biz_pei',     label: 'PEI',                type: 'spolka',    v: ['biznesy','zespol'], desc: 'Partner Expert Investments — inwestycje, consulting' },
  { id: 'biz_peo',     label: 'PEO',                type: 'spolka',    v: ['biznesy','zespol'], desc: 'Partner Expert Operator — zarządzanie hotelami/apartamentami' },
  { id: 'biz_per',     label: 'PER',                type: 'spolka',    v: ['biznesy','zespol'], desc: 'Partner Expert Restaurants — gastronomia, restrukturyzacja w toku' },
  // Punkty
  { id: 'biz_indu',    label: 'IND.U',              type: 'punkt',     v: ['biznesy','zespol'], desc: 'Apartamenty — induapartamenty.pl' },
  { id: 'biz_sunday',  label: 'Sunday',             type: 'punkt',     v: ['biznesy','zespol'], desc: 'Sunday Resort — sundayresort.online' },
  { id: 'biz_gea',     label: 'GEA Sea & Resort',   type: 'punkt',     v: ['biznesy','zespol'], desc: 'W przygotowaniu' },
  { id: 'biz_spot',    label: 'Lobby Bar / Spot',   type: 'punkt',     v: ['biznesy','zespol'], desc: 'IND.U Spot / Lobby Bar' },
  { id: 'biz_muszla',  label: 'Muszla',             type: 'punkt',     v: ['biznesy','zespol'], desc: 'Muszla Koncertowa — muszlakolobrzeg.pl, dzierżawa od miasta' },
  { id: 'biz_beachbox',label: 'Beach Box',          type: 'punkt',     v: ['biznesy','zespol'], desc: 'Beach Box — gastronomia plazowa' },
  { id: 'biz_sunset',  label: 'Sunset',             type: 'punkt',     v: ['biznesy','zespol'], desc: 'Sunset Bar' },
  // Strategia aktywna
  { id: 'str_noraco',  label: 'Noraco',             type: 'strategia', v: ['biznesy'], desc: 'W trakcie' },
  { id: 'str_leba',    label: 'Leba',               type: 'strategia', v: ['biznesy'], desc: 'Umowa podpisana' },
  { id: 'str_rogowo',  label: 'Rogowo 60',          type: 'strategia', v: ['biznesy'], desc: 'Umowa podpisana' },
  { id: 'str_wildpearl',label:'Wild Pearl',          type: 'strategia', v: ['biznesy'], desc: 'Umowa podpisana' },
  { id: 'str_area',    label: 'Area na Plazowej',   type: 'strategia', v: ['biznesy'], desc: 'W trakcie' },
  { id: 'str_grzybowo',label: 'Dzialka Grzybowo',   type: 'strategia', v: ['biznesy'], desc: 'W trakcie' },
  { id: 'str_biedronka',label:'Dzialka Biedronka',   type: 'strategia', v: ['biznesy'], desc: 'W trakcie' },
  { id: 'str_foodhall',label: 'Food Hall w Porcie', type: 'strategia', v: ['biznesy'], desc: 'Pauza' },
  { id: 'str_celka',   label: 'CELKA 500 APT',      type: 'strategia', v: ['biznesy'], desc: 'Pauza' },
  { id: 'str_p50',     label: 'P50',                type: 'strategia', v: ['biznesy'], desc: 'Pauza' },

  // ========== ZESPÓŁ VIEW (nested: spółka → punkt → osoba) ==========
  { id: 'grp_pei', label: 'PEI (3)', type: 'group', v: ['zespol'], desc: 'Partner Expert Investments — 3 pracowników' },
  { id: 'grp_peo', label: 'PEO (5)', type: 'group', v: ['zespol'], desc: 'Partner Expert Operator — 5 pracowników' },
  { id: 'grp_peo_indu', label: 'IND.U (4)', type: 'group', v: ['zespol'], desc: 'IND.U — 4 pracowników', parent: 'grp_peo' },
  { id: 'grp_peo_sunday', label: 'Sunday (1)', type: 'group', v: ['zespol'], desc: 'Sunday — 1 pracownik', parent: 'grp_peo' },
  { id: 'grp_per', label: 'PER (22)', type: 'group', v: ['zespol'], desc: 'Partner Expert Restaurants — 22 pracowników' },
  { id: 'grp_per_beachbox', label: 'Beach Box (8)', type: 'group', v: ['zespol'], desc: 'Beach Box — 8 pracowników', parent: 'grp_per' },
  { id: 'grp_per_muszla', label: 'Muszla (5)', type: 'group', v: ['zespol'], desc: 'Muszla Koncertowa — 5 pracowników', parent: 'grp_per' },
  { id: 'grp_per_technika', label: 'Technika cross-venue (5)', type: 'group', v: ['zespol'], desc: '5 techników obsługujących wszystkie punkty PER', parent: 'grp_per' },
  { id: 'grp_per_lobby', label: 'Lobby Bar / Spot (2)', type: 'group', v: ['zespol'], desc: 'Lobby Bar / Spot — 2 pracowników', parent: 'grp_per' },
  { id: 'grp_per_sunset', label: 'Sunset (1)', type: 'group', v: ['zespol'], desc: 'Sunset — 1 pracownik', parent: 'grp_per' },
  { id: 'grp_per_indu', label: 'IND.U technika (1)', type: 'group', v: ['zespol'], desc: 'IND.U — 1 technik (spółka PER)', parent: 'grp_per' },
  // Pracownicy aktywni
  { id: 'p_adrianszufel', label: 'Adrian Szufel', type: 'person_zarzad', v: ['zespol'], desc: 'Członek zarządu | Zarząd | szufel@partnerexpert.pl', parent: 'grp_pei' },
  { id: 'p_irminaandrzejczuk', label: 'Irmina Andrzejczuk', type: 'person_zarzad', v: ['zespol'], desc: 'Dyrektor Zarządzający PER | Zarząd | irmina.andrzejczuk@partnerexpert.pl', parent: 'grp_per_beachbox' },
  { id: 'p_oliverandrzejczuk', label: 'Oliver Andrzejczuk', type: 'person_zarzad', v: ['zespol'], desc: 'Członek zarządu | Zarząd | andrzejczuk@partnerexpert.pl', parent: 'grp_pei' },
  { id: 'p_patrycjafurmankiewic', label: 'Patrycja Furmankiewicz', type: 'person_zarzad', v: ['zespol'], desc: 'Dyrektor Operacyjny PEO | Zarząd | furmankiewicz@partnerexpert.pl', parent: 'grp_peo_indu' },
  { id: 'p_urszulakokoszczyk', label: 'Urszula Kokoszczyk', type: 'person_zarzad', v: ['zespol'], desc: 'Dyrektor Muszla Koncertowa | Zarząd | kokoszczyk@partnerexpert.pl', parent: 'grp_per_muszla' },
  { id: 'p_kamilaszczutkowska', label: 'Kamila Szczutkowska', type: 'person_management', v: ['zespol'], desc: 'Manager ds. Finansowych | Management | szczutkowska@partnerexpert.pl', parent: 'grp_pei' },
  { id: 'p_majalimanska', label: 'Maja Limańska', type: 'person_management', v: ['zespol'], desc: 'Project Manager PEO | Management | limanska@partnerexpert.pl', parent: 'grp_peo_sunday' },
  { id: 'p_beatakasprzak', label: 'Beata Kasprzak', type: 'person_kierownicy', v: ['zespol'], desc: 'House Keeping Manager | Kierownicy', parent: 'grp_peo_indu' },
  { id: 'p_buchutadorota', label: 'Buchuta Dorota', type: 'person_kierownicy', v: ['zespol'], desc: 'Kierownik baru | Kierownicy | buchuta@partnerexpert.pl', parent: 'grp_per_sunset' },
  { id: 'p_oliwiawojcik', label: 'Oliwia Wójcik', type: 'person_kierownicy', v: ['zespol'], desc: 'Kierownik baru | Kierownicy', parent: 'grp_per_beachbox' },
  { id: 'p_patrycjakozbial', label: 'Patrycja Koźbiał', type: 'person_kierownicy', v: ['zespol'], desc: 'Kierownik baru | Kierownicy', parent: 'grp_per_muszla' },
  { id: 'p_dorotakornas', label: 'Dorota Kornas', type: 'person_specjalisci', v: ['zespol'], desc: 'Koordynator ds. Wynajmu Apartamentów | Specjaliści | kornas@partnerexpert.pl', parent: 'grp_peo_indu' },
  { id: 'p_anastasiiamakedonska', label: 'Anastasiia Makedonska', type: 'person_pracownik_liniowy', v: ['zespol'], desc: 'Pracownik baru | Liniowy', parent: 'grp_per_beachbox' },
  { id: 'p_bartoszpietrasiak', label: 'Bartosz Pietrasiak', type: 'person_pracownik_liniowy', v: ['zespol'], desc: 'Elektryk B2B | Liniowy', parent: 'grp_per_technika' },
  { id: 'p_bogdanbelej', label: 'Bogdan Bełej', type: 'person_pracownik_liniowy', v: ['zespol'], desc: 'Pracownik techniczny | Liniowy', parent: 'grp_per_technika' },
  { id: 'p_dariacieslak', label: 'Daria Cieślak', type: 'person_pracownik_liniowy', v: ['zespol'], desc: 'Pracownik kuchnia | Liniowy', parent: 'grp_per_lobby' },
  { id: 'p_innakvasnikowa', label: 'Inna Kvasnikowa', type: 'person_pracownik_liniowy', v: ['zespol'], desc: 'Pracownik kuchnia | Liniowy', parent: 'grp_per_beachbox' },
  { id: 'p_irynashestakowa', label: 'Iryna Shestakowa', type: 'person_pracownik_liniowy', v: ['zespol'], desc: 'Pracownik kuchnia | Liniowy', parent: 'grp_per_beachbox' },
  { id: 'p_juliamalecka', label: 'Julia Małecka', type: 'person_pracownik_liniowy', v: ['zespol'], desc: 'Pracownik baru | Liniowy', parent: 'grp_per_muszla' },
  { id: 'p_kaletakamil', label: 'Kamil Kaleta', type: 'person_pracownik_liniowy', v: ['zespol'], desc: 'Pracownik kuchnia | Liniowy', parent: 'grp_per_muszla' },
  { id: 'p_katarzynamatyjaszczy', label: 'Katarzyna Matyjaszczyk', type: 'person_pracownik_liniowy', v: ['zespol'], desc: 'Pracownik kuchnia | Liniowy', parent: 'grp_per_lobby' },
  { id: 'p_krystiangaik', label: 'Krystian Gaik', type: 'person_pracownik_liniowy', v: ['zespol'], desc: 'B2B, zewnętrzny (~70% PEG) | Liniowy', parent: 'grp_per_technika' },
  { id: 'p_krzysztofseralis', label: 'Krzysztof Seralis', type: 'person_pracownik_liniowy', v: ['zespol'], desc: 'Pracownik kuchnia | Liniowy', parent: 'grp_per_muszla' },
  { id: 'p_mateuszkasprzak', label: 'Mateusz Kasprzak', type: 'person_pracownik_liniowy', v: ['zespol'], desc: 'Pracownik techniczny | Liniowy', parent: 'grp_per_indu' },
  { id: 'p_paularyzewskakorzen', label: 'Paula Ryżewska-Korzeń', type: 'person_pracownik_liniowy', v: ['zespol'], desc: 'Asystentka Sekretariatu | Liniowy | ryzewska-korzen@partnerexpert.pl', parent: 'grp_peo_indu' },
  { id: 'p_tadeuszzaborowski', label: 'Tadeusz Zaborowski', type: 'person_pracownik_liniowy', v: ['zespol'], desc: 'Pracownik techniczny | Liniowy', parent: 'grp_per_technika' },
  { id: 'p_tetianapoklad', label: 'Tetiana Poklad', type: 'person_pracownik_liniowy', v: ['zespol'], desc: 'Pracownik kuchnia | Liniowy', parent: 'grp_per_beachbox' },
  { id: 'p_tomaszciecwierski', label: 'Tomasz Ciećwierski', type: 'person_pracownik_liniowy', v: ['zespol'], desc: 'Pracownik techniczny | Liniowy', parent: 'grp_per_technika' },
  { id: 'p_vasylkharskyy', label: 'Vasyl Kharskyy', type: 'person_pracownik_liniowy', v: ['zespol'], desc: 'Stróż | Liniowy', parent: 'grp_per_beachbox' },
  { id: 'p_viktoriakulchytskavo', label: 'Viktoria Kulchytska-Vouchko', type: 'person_pracownik_liniowy', v: ['zespol'], desc: 'Pracownik baru | Liniowy', parent: 'grp_per_beachbox' },
];

const edges = [
  // ========== CORTEX EDGES ==========
  { source: 'update_context_py', target: 'context_md',      label: 'generates', v: ['cortex'] },
  // Repo Cortex — strukturalne edges (nie wszystkie skrypty, tylko główne kawałki)
  { source: 'repo_cortex', target: 'claude_md',     label: 'contains', v: ['cortex'] },
  { source: 'repo_cortex', target: 'context_md',    label: 'contains', v: ['cortex'] },
  { source: 'repo_cortex', target: 'env_file',      label: 'contains', v: ['cortex'] },
  { source: 'repo_cortex', target: 'knowledge_dir', label: 'contains', v: ['cortex'] },
  { source: 'repo_cortex', target: 'venv',          label: 'contains', v: ['cortex'] },
  // Knowledge dir — zawartość
  { source: 'knowledge_dir', target: 'notion_map',     label: 'mapa',    v: ['cortex'] },
  { source: 'knowledge_dir', target: 'ecosystem_map',  label: 'mapa',    v: ['cortex'] },
  { source: 'knowledge_dir', target: 'apps_map',      label: 'mapa',    v: ['cortex'] },
  { source: 'knowledge_dir', target: 'adi_psychology', label: 'profil',  v: ['cortex'] },
  { source: 'knowledge_dir', target: 'quotes_mazur',   label: 'cytaty',  v: ['cortex'] },
  // Atlas — osobny repo
  { source: 'mcp_chrome',     target: 'laptop',          label: 'browser',  v: ['cortex'] },
  { source: 'mcp_canva',      target: 'laptop',          label: 'MCP w chat', v: ['cortex'] },
  { source: 'mcp_notion_ai',  target: 'notion_api_firm', label: 'proxies',  v: ['cortex'] },
  { source: 'mcp_notion_ai',  target: 'notion_api_priv', label: 'proxies',  v: ['cortex'] },
  { source: 'gmail_py',          target: 'gmail_api',       label: 'OAuth',       v: ['cortex'] },
  { source: 'calendar_py',       target: 'calendar_api',    label: 'OAuth',       v: ['cortex'] },
  { source: 'notion_py',         target: 'notion_api_firm', label: 'token',       v: ['cortex'] },
  { source: 'notion_py',         target: 'notion_api_priv', label: 'token',       v: ['cortex'] },
  { source: 'notion2email_py',   target: 'notion_api_firm', label: 'read',        v: ['cortex'] },
  { source: 'notion2email_py',   target: 'gmail_api',       label: 'draft/send',  v: ['cortex'] },
  { source: 'cloudflare_py',     target: 'cloudflare_api',  label: 'token',       v: ['cortex'] },
  { source: 'seo_report_py',     target: 'cloudflare_api',  label: 'analytics',   v: ['cortex'] },
  { source: 'seo_report_py',     target: 'psi_api',         label: 'scores',      v: ['cortex'] },
  { source: 'seo_report_py',     target: 'notion_api_firm', label: 'write',       v: ['cortex'] },
  { source: 'health_check_py',   target: 'notion_api_firm', label: 'smoke',       v: ['cortex'] },
  { source: 'health_check_py',   target: 'gmail_api',       label: 'smoke',       v: ['cortex'] },
  { source: 'fireflies_py',      target: 'fireflies_api',   label: 'transcripts', v: ['cortex'] },
  { source: 'fireflies_py',      target: 'openai_api',      label: 'summarize',   v: ['cortex'] },
  { source: 'fireflies_py',      target: 'notion_api_firm', label: 'write',       v: ['cortex'] },
  { source: 'google_ads_py',     target: 'google_ads_api',  label: 'campaigns',   v: ['cortex'] },
  { source: 'ga4_py',            target: 'ga4_api',         label: 'analytics',   v: ['cortex'] },
  { source: 'search_console_py', target: 'gsc_api',         label: 'positions',   v: ['cortex'] },
  { source: 'deploy_ftp_sh',     target: 'dhosting_ftp',    label: 'FTP push',    v: ['cortex'] },
  { source: 'update_context_py', target: 'notion_api_firm', label: 'read',        v: ['cortex'] },
  { source: 'update_context_py', target: 'notion_api_priv', label: 'read',        v: ['cortex'] },
  { source: 'update_context_py', target: 'gmail_api',       label: 'inbox',       v: ['cortex'] },
  { source: 'update_context_py', target: 'calendar_api',    label: 'events',      v: ['cortex'] },
  { source: 'smoke_test_py',     target: 'notion_api_firm', label: 'test',        v: ['cortex'] },
  { source: 'smoke_test_py',     target: 'gmail_api',       label: 'test',        v: ['cortex'] },
  { source: 'google_admin_py',  target: 'google_admin_api',label: 'SDK',         v: ['cortex'] },
  { source: 'indexing_py',      target: 'indexing_api',    label: 'submit',      v: ['cortex'] },
  { source: 'app_janusz',  target: 'mikrus',           label: 'deploy',   v: ['cortex'] },
  { source: 'repo_gustaw', target: 'app_gustaw',       label: 'builds',   v: ['cortex'] },
  { source: 'app_bot_voice', target: 'vercel',         label: 'deploy',   v: ['cortex'] },
  { source: 'timer_context', target: 'update_context_py', label: 'triggers', v: ['cortex'] },
  { source: 'timer_smoke',   target: 'smoke_test_py',     label: 'triggers', v: ['cortex'] },
  { source: 'timer_seo',     target: 'seo_report_py',     label: 'triggers', v: ['cortex'] },
  { source: 'timer_claude_backup', target: 'gcp_bucket', label: 'upload ~/.claude/', v: ['cortex'] },
  { source: 'mcp_notion_firm', target: 'notion_api_firm', label: 'proxies', v: ['cortex'] },
  { source: 'mcp_notion_priv', target: 'notion_api_priv', label: 'proxies', v: ['cortex'] },
  { source: 'mcp_gmail',       target: 'gmail_api',       label: 'proxies', v: ['cortex'] },
  { source: 'mcp_calendar',    target: 'calendar_api',    label: 'proxies', v: ['cortex'] },
  { source: 'mcp_fireflies',   target: 'fireflies_api',   label: 'proxies', v: ['cortex'] },
  { source: 'app_pm',       target: 'supabase',    label: 'DB cen',     v: ['cortex'] },
  { source: 'app_pm',       target: 'openai_api',  label: 'summaries',  v: ['cortex'] },
  { source: 'app_pm',       target: 'apify',       label: 'scraping',   v: ['cortex'] },
  { source: 'app_zakupex',  target: 'supabase',    label: 'DB faktur',  v: ['cortex'] },
  { source: 'app_janusz',   target: 'mikrus_pg',   label: 'messages+timecard', v: ['cortex'] },
  { source: 'app_janusz',   target: 'notion_api_firm', label: 'Wiki',   v: ['cortex'] },
  { source: 'app_janusz',   target: 'openai_api',  label: 'GPT',        v: ['cortex'] },
  { source: 'app_bot_voice', target: 'notion_api_firm', label: 'zapis', v: ['cortex'] },
  { source: 'app_bot_voice', target: 'openai_api', label: 'Whisper',    v: ['cortex'] },
  { source: 'app_gustaw',   target: 'openai_api',  label: 'GPT/Gemini', v: ['cortex'] },
  { source: 'app_gustaw',   target: 'notion_api_firm', label: 'sync',  v: ['cortex'] },
  { source: 'repo_pm',       target: 'app_pm',       label: 'builds', v: ['cortex'] },
  { source: 'repo_zakupex',  target: 'app_zakupex',  label: 'builds', v: ['cortex'] },
  { source: 'repo_janusz',   target: 'app_janusz',   label: 'builds', v: ['cortex'] },
  { source: 'repo_muszla',   target: 'app_muszla',   label: 'builds', v: ['cortex'] },
  { source: 'repo_voice',    target: 'app_bot_voice', label: 'builds',v: ['cortex'] },
  { source: 'app_pm',      target: 'vercel',  label: 'deploy', v: ['cortex'] },
  { source: 'app_zakupex', target: 'vercel',  label: 'deploy', v: ['cortex'] },
  { source: 'app_muszla',  target: 'vercel',  label: 'deploy', v: ['cortex'] },
  { source: 'deploy_ftp_sh', target: 'dhosting', label: 'FTP',  v: ['cortex'] },
  { source: 'laptop', target: 'timer_context', label: 'runs', v: ['cortex'] },
  { source: 'laptop', target: 'timer_smoke',   label: 'runs', v: ['cortex'] },
  { source: 'laptop', target: 'timer_seo',     label: 'runs', v: ['cortex'] },
  { source: 'laptop', target: 'timer_claude_backup', label: 'runs', v: ['cortex'] },

  // Nowe skrypty → repo
  { source: 'gbp_py',             target: 'gbp_api',       label: 'OAuth',      v: ['cortex'] },
  { source: 'content_pipeline_py',target: 'openai_api',     label: 'Whisper+GPT',v: ['cortex'] },
  { source: 'content_pipeline_py',target: 'fb_api',         label: 'publish',    v: ['cortex'] },
  { source: 'check_treningi_py', target: 'notion_api_priv',label: 'read',       v: ['cortex'] },
  { source: 'update_supl_py',    target: 'notion_api_priv',label: 'write',      v: ['cortex'] },
  { source: 'notion_replace_py', target: 'notion_api_firm',label: 'replace',    v: ['cortex'] },
  { source: 'seo_report_py',     target: 'gsc_api',        label: 'positions',  v: ['cortex'] },
  { source: 'seo_report_py',     target: 'ga4_api',        label: 'analytics',  v: ['cortex'] },
  { source: 'app_muszla',        target: 'biz_muszla',     label: 'strona WWW', v: ['biznesy'] },
  // Archiwista (jedyny cron na Mikrusie)
  { source: 'cron_archiwista',    target: 'archiwista_sh',    label: 'triggers', v: ['cortex'] },
  { source: 'mikrus', target: 'cron_archiwista', label: 'cron', v: ['cortex'] },
  { source: 'archiwista_sh', target: 'strych',     label: 'backup',  v: ['cortex'] },
  { source: 'archiwista_sh', target: 'gcp_bucket', label: 'backup 2/2', v: ['cortex'] },
  { source: 'archiwista_sh', target: 'mikrus_pg',  label: 'pg_dump', v: ['cortex'] },
  // Persony → Mikrus
  { source: 'app_gustaw', target: 'mikrus', label: 'deploy', v: ['cortex'] },
  // GCP — struktura
  { source: 'gcp', target: 'gcp_sm',     label: 'has', v: ['cortex'] },
  { source: 'gcp', target: 'gcp_bucket', label: 'has', v: ['cortex'] },
  { source: 'gcp', target: 'gcp_ar',     label: 'has', v: ['cortex'] },
  { source: 'gcp', target: 'gcp_uptime', label: 'has', v: ['cortex'] },
  { source: 'gcp', target: 'cr_notion_backup',    label: 'runs', v: ['cortex'] },
  { source: 'gcp', target: 'cr_supabase_backup',  label: 'runs', v: ['cortex'] },
  { source: 'gcp', target: 'cr_cloudflare_backup',label: 'runs', v: ['cortex'] },
  { source: 'gcp', target: 'cr_recenzent',        label: 'runs', v: ['cortex'] },
  { source: 'gcp', target: 'cr_content',          label: 'runs Job', v: ['cortex'] },
  // Schedulery → CR
  { source: 'sch_notion',     target: 'cr_notion_backup',    label: 'triggers', v: ['cortex'] },
  { source: 'sch_supabase',   target: 'cr_supabase_backup',  label: 'triggers', v: ['cortex'] },
  { source: 'sch_cf',         target: 'cr_cloudflare_backup',label: 'triggers', v: ['cortex'] },
  { source: 'sch_recenzent',  target: 'cr_recenzent',        label: 'triggers', v: ['cortex'] },
  { source: 'sch_content',    target: 'cr_content',          label: 'triggers', v: ['cortex'] },
  { source: 'sch_pm_scan',    target: 'app_pm',              label: 'HTTP GET', v: ['cortex'] },
  { source: 'sch_pm_summary', target: 'app_pm',              label: 'HTTP GET', v: ['cortex'] },
  { source: 'sch_pm_retry',   target: 'app_pm',              label: 'HTTP GET', v: ['cortex'] },
  // GCP → secret consumers
  { source: 'gcp_sm', target: 'cr_notion_backup',     label: 'secrets', v: ['cortex'] },
  { source: 'gcp_sm', target: 'cr_supabase_backup',   label: 'secrets', v: ['cortex'] },
  { source: 'gcp_sm', target: 'cr_cloudflare_backup', label: 'secrets', v: ['cortex'] },
  { source: 'gcp_sm', target: 'cr_recenzent',         label: 'secrets', v: ['cortex'] },
  { source: 'gcp_sm', target: 'cr_content',           label: 'secrets', v: ['cortex'] },
  // CR Functions → APIs
  { source: 'cr_notion_backup',    target: 'notion_api_firm', label: 'backup', v: ['cortex'] },
  { source: 'cr_notion_backup',    target: 'notion_api_priv', label: 'backup', v: ['cortex'] },
  { source: 'cr_notion_backup',    target: 'gcp_bucket',      label: 'write',  v: ['cortex'] },
  { source: 'cr_supabase_backup',  target: 'supabase',        label: 'dump',   v: ['cortex'] },
  { source: 'cr_supabase_backup',  target: 'gcp_bucket',      label: 'write',  v: ['cortex'] },
  { source: 'cr_cloudflare_backup',target: 'cloudflare_api',  label: 'dump',   v: ['cortex'] },
  { source: 'cr_cloudflare_backup',target: 'gcp_bucket',      label: 'write',  v: ['cortex'] },
  { source: 'cr_recenzent',        target: 'gbp_api',         label: 'reviews',v: ['cortex'] },
  { source: 'cr_recenzent',        target: 'openai_api',      label: 'GPT reply', v: ['cortex'] },
  { source: 'cr_recenzent',        target: 'app_janusz',      label: 'raport WA', v: ['cortex'] },
  { source: 'cr_content',          target: 'openai_api',      label: 'Whisper+GPT', v: ['cortex'] },
  { source: 'cr_content',          target: 'gdrive_api',      label: 'rolki Shared Drive', v: ['cortex'] },
  { source: 'cr_content',          target: 'notion_api_firm', label: 'Social Planner', v: ['cortex'] },
  { source: 'gcp_ar',              target: 'cr_content',      label: 'Docker image', v: ['cortex'] },
  // Uptime monitoring
  { source: 'gcp_uptime', target: 'app_janusz', label: 'health check', v: ['cortex'] },
  // Persony → Mikrus
  { source: 'app_gustaw', target: 'mikrus', label: 'deploy', v: ['cortex'] },

  // ========== BIZNESY EDGES ==========
  { source: 'biz_peg', target: 'biz_pei',     label: '', v: ['biznesy','zespol'] },
  { source: 'biz_peg', target: 'biz_peo',     label: '', v: ['biznesy','zespol'] },
  { source: 'biz_peg', target: 'biz_per',     label: '', v: ['biznesy','zespol'] },
  { source: 'biz_peo', target: 'biz_indu',    label: '', v: ['biznesy','zespol'] },
  { source: 'biz_peo', target: 'biz_sunday',  label: '', v: ['biznesy','zespol'] },
  { source: 'biz_peo', target: 'biz_gea',     label: '', v: ['biznesy','zespol'] },
  { source: 'biz_peo', target: 'biz_spot',    label: '', v: ['biznesy','zespol'] },
  { source: 'biz_per', target: 'biz_muszla',  label: '', v: ['biznesy','zespol'] },
  { source: 'biz_per', target: 'biz_beachbox',label: '', v: ['biznesy','zespol'] },
  { source: 'biz_per', target: 'biz_sunset',  label: '', v: ['biznesy','zespol'] },
  // Strategia -> PEI
  { source: 'biz_pei', target: 'str_noraco',   label: 'w trakcie',  v: ['biznesy'] },
  { source: 'biz_pei', target: 'str_leba',     label: 'umowa',      v: ['biznesy'] },
  { source: 'biz_pei', target: 'str_rogowo',   label: 'umowa',      v: ['biznesy'] },
  { source: 'biz_pei', target: 'str_wildpearl',label: 'umowa',      v: ['biznesy'] },
  { source: 'biz_pei', target: 'str_area',     label: 'w trakcie',  v: ['biznesy'] },
  { source: 'biz_pei', target: 'str_grzybowo', label: 'w trakcie',  v: ['biznesy'] },
  { source: 'biz_pei', target: 'str_biedronka',label: 'w trakcie',  v: ['biznesy'] },
  { source: 'biz_pei', target: 'str_foodhall', label: 'pauza',      v: ['biznesy'] },
  { source: 'biz_pei', target: 'str_celka',    label: 'pauza',      v: ['biznesy'] },
  { source: 'biz_pei', target: 'str_p50',      label: 'pauza',      v: ['biznesy'] },

  // ========== ZESPÓŁ EDGES — hierarchia ==========
  // Zarząd / Management w grupie → podwładni
  // Adi/Oliver/Kamila w PEI (holding)
  { source: 'p_adrianszufel',      target: 'p_oliverandrzejczuk', label: 'co-owner',  v: ['zespol'] },
  { source: 'p_adrianszufel',      target: 'p_kamilaszczutkowska',label: 'finanse',   v: ['zespol'] },
  { source: 'p_adrianszufel',      target: 'p_patrycjafurmankiewic', label: 'PEO',    v: ['zespol'] },
  { source: 'p_adrianszufel',      target: 'p_urszulakokoszczyk', label: 'Muszla',    v: ['zespol'] },
  { source: 'p_adrianszufel',      target: 'p_irminaandrzejczuk', label: 'Beach Box', v: ['zespol'] },
  // Patrycja F. → IND.U + Sunday
  { source: 'p_patrycjafurmankiewic', target: 'p_dorotakornas',   label: 'PEO',       v: ['zespol'] },
  { source: 'p_patrycjafurmankiewic', target: 'p_beatakasprzak',  label: 'HK',        v: ['zespol'] },
  { source: 'p_patrycjafurmankiewic', target: 'p_paularyzewskakorzen', label: 'admin',v: ['zespol'] },
  { source: 'p_patrycjafurmankiewic', target: 'p_mateuszkasprzak',label: 'technik',   v: ['zespol'] },
  { source: 'p_patrycjafurmankiewic', target: 'p_majalimanska',   label: 'PM',        v: ['zespol'] },
  // Irmina → Beach Box
  { source: 'p_irminaandrzejczuk', target: 'p_oliwiawojcik',       label: 'bar BB',    v: ['zespol'] },
  { source: 'p_oliwiawojcik',      target: 'p_anastasiiamakedonska', label: '',        v: ['zespol'] },
  { source: 'p_oliwiawojcik',      target: 'p_viktoriakulchytskavo', label: '',        v: ['zespol'] },
  { source: 'p_irminaandrzejczuk', target: 'p_tetianapoklad',     label: 'kuchnia',   v: ['zespol'] },
  { source: 'p_irminaandrzejczuk', target: 'p_innakvasnikowa',    label: '',          v: ['zespol'] },
  { source: 'p_irminaandrzejczuk', target: 'p_irynashestakowa',   label: '',          v: ['zespol'] },
  { source: 'p_irminaandrzejczuk', target: 'p_vasylkharskyy',     label: 'stróż',     v: ['zespol'] },
  // Ula → Muszla
  { source: 'p_urszulakokoszczyk', target: 'p_patrycjakozbial',   label: 'bar',       v: ['zespol'] },
  { source: 'p_patrycjakozbial',   target: 'p_juliamalecka',      label: '',          v: ['zespol'] },
  { source: 'p_urszulakokoszczyk', target: 'p_krzysztofseralis',  label: 'kuchnia',   v: ['zespol'] },
  { source: 'p_urszulakokoszczyk', target: 'p_kaletakamil',       label: '',          v: ['zespol'] },
  // Buchuta Dorota → Sunset (jedna osoba grupy, raportuje do Irminy/Uli)
  { source: 'p_irminaandrzejczuk', target: 'p_buchutadorota',     label: 'Sunset',    v: ['zespol'] },
  // PER cross-venue (technika) — raportują do Olivera (ops)
  { source: 'p_oliverandrzejczuk', target: 'p_tomaszciecwierski', label: 'technik',   v: ['zespol'] },
  { source: 'p_oliverandrzejczuk', target: 'p_bogdanbelej',       label: 'technik',   v: ['zespol'] },
  { source: 'p_oliverandrzejczuk', target: 'p_tadeuszzaborowski', label: 'technik',   v: ['zespol'] },
  { source: 'p_oliverandrzejczuk', target: 'p_bartoszpietrasiak', label: 'B2B elektryk', v: ['zespol'] },
  { source: 'p_oliverandrzejczuk', target: 'p_krystiangaik',      label: 'B2B',       v: ['zespol'] },
  // Lobby Bar/Spot → Patrycja F. (PEO)
  { source: 'p_patrycjafurmankiewic', target: 'p_dariacieslak',     label: 'Spot',    v: ['zespol'] },
  { source: 'p_patrycjafurmankiewic', target: 'p_katarzynamatyjaszczy', label: 'Spot', v: ['zespol'] },
];
