
// Layer groups — compound parent nodes (visual grouping)
const layers = [
  { id: 'L_GCP',      label: '☁️ Google Cloud Platform',  v: ['cortex'], desc: 'Wszystkie crony + backupy + monitoring. Project: ai-council-487609. Koszt ~10-12 zł/mies.' },
  { id: 'L_MIKRUS',   label: '🐧 Mikrus VPS',              v: ['cortex'], desc: 'Persistent WA sesje + on-host pg_dump. leszek140, 20 zł/mies.' },
  { id: 'L_LAPTOP',   label: '💻 Laptop (penguin)',        v: ['cortex'], desc: 'Praca interaktywna. Cortex runtime. ZERO cronów produkcyjnych.' },
  { id: 'L_VERCEL',   label: '▲ Vercel',                  v: ['cortex'], desc: 'Apki frontend/backend Next.js.' },
  { id: 'L_DHOSTING', label: '🌐 Dhosting',                v: ['cortex'], desc: 'Statyczne strony WWW. Crony PHP zablokowane.' },
];

// Node → Layer mapping (ktory node do ktorej warstwy)
const nodeToLayer = {
  // GCP
  gcp: 'L_GCP', gcp_sm: 'L_GCP', gcp_bucket: 'L_GCP', gcp_ar: 'L_GCP', gcp_uptime: 'L_GCP',
  gcp_bq: 'L_GCP',
  cr_notion_backup: 'L_GCP', cr_supabase_backup: 'L_GCP', cr_cloudflare_backup: 'L_GCP',
  cr_recenzent: 'L_GCP', cr_content: 'L_GCP',
  cr_health_check: 'L_GCP', cr_workspace_audit: 'L_GCP', cr_indexing: 'L_GCP',
  cr_zakupex_import: 'L_GCP', cr_janusz_content: 'L_GCP', cr_janusz_weekly: 'L_GCP',
  sch_notion: 'L_GCP', sch_supabase: 'L_GCP', sch_cf: 'L_GCP', sch_recenzent: 'L_GCP',
  sch_content: 'L_GCP', sch_pm_scan: 'L_GCP', sch_pm_summary: 'L_GCP', sch_pm_retry: 'L_GCP',
  sch_health_check: 'L_GCP', sch_health_digest: 'L_GCP', sch_workspace_audit: 'L_GCP',
  sch_indexing: 'L_GCP', sch_zakupex_import: 'L_GCP', sch_janusz_content: 'L_GCP', sch_janusz_weekly: 'L_GCP', sch_janusz_daily: 'L_GCP',
  sch_content_publish: 'L_GCP',
  // Mikrus
  mikrus: 'L_MIKRUS', app_janusz: 'L_MIKRUS', app_gustaw: 'L_MIKRUS',
  mikrus_pg: 'L_MIKRUS', cron_archiwista: 'L_MIKRUS', archiwista_sh: 'L_MIKRUS', strych: 'L_MIKRUS',
  // Laptop
  laptop: 'L_LAPTOP', timer_context: 'L_LAPTOP', timer_smoke: 'L_LAPTOP',
  timer_seo: 'L_LAPTOP', timer_claude_backup: 'L_LAPTOP', env_file: 'L_LAPTOP',
  repo_cortex: 'L_LAPTOP', claude_md: 'L_LAPTOP', context_md: 'L_LAPTOP',
  knowledge_dir: 'L_LAPTOP', venv: 'L_LAPTOP',
  notion_map: 'L_LAPTOP', ecosystem_map: 'L_LAPTOP', apps_map: 'L_LAPTOP',
  quotes_mazur: 'L_LAPTOP', adi_psychology: 'L_LAPTOP',
  www_atlas: 'L_LAPTOP',
  // Vercel
  vercel: 'L_VERCEL', app_pm: 'L_VERCEL', www_muszla: 'L_VERCEL',
  // Zakupex — Cloud Run europe-west1 (migrowane z Vercel 2026-04-13)
  app_zakupex: 'L_GCP',
  // Nowe Cloud Run (2026-04-17+)
  cr_atlas_status: 'L_GCP',
  // Dhosting
  dhosting: 'L_DHOSTING',
};

// v = views this node belongs to
const nodes = [
  // ========== CORTEX VIEW ==========
  // Core files
  { id: 'claude_md',         label: 'CLAUDE.md',             type: 'core',   v: ['cortex'], desc: 'Główne instrukcje Cortexu — tryby, formaty, trigger phrases, harmonogram briefingów' },
  { id: 'context_md',        label: 'context.md',            type: 'core',   v: ['cortex'], desc: 'Kontekst dnia — generowany o 07:00. Kalendarz (PEG+prywatny+rodzinny), zadania, CRM, habits, inbox (2 konta)' },
  { id: 'env_file',          label: '.env',                  type: 'core',   v: ['cortex'], desc: 'Tokeny i klucze API — Notion (2x), Gmail, Cloudflare, OpenAI, Google Ads, Fireflies' },
  { id: 'knowledge_dir',     label: 'knowledge/',            type: 'core',   v: ['cortex'], desc: 'Baza wiedzy: agents/, maps/, www/, apps/' },
  { id: 'quotes_mazur',      label: 'quotes_mazur.md',       type: 'core',   v: ['cortex'], desc: 'Cytaty Mazura — konfrontacja, mobilizacja, kotwica' },
  { id: 'adi_psychology',    label: 'adi_psychology.md',      type: 'core',   v: ['cortex'], desc: 'Profil psychologiczny — reset, triage, strategia' },
  { id: 'notion_map',        label: 'notion_map.md',         type: 'core',   v: ['cortex'], desc: 'Mapa 32 baz Notion — ID, relacje, statusy' },
  { id: 'ecosystem_map',     label: 'ecosystem_map.md',      type: 'core',   v: ['cortex'], desc: 'Pełna mapa ekosystemu PEG' },
  { id: 'apps_map',          label: 'apps_map.md',           type: 'core',   v: ['cortex'], desc: 'Mapa aplikacji ~/APP' },
  { id: 'venv',              label: 'scripts/venv/',         type: 'core',   v: ['cortex'], desc: 'Python virtualenv' },

  // Scripts
  { id: 'gmail_py',          label: 'gmail.py',              type: 'script', v: ['cortex'], desc: 'list, read, send, draft, search [--private]' },
  { id: 'calendar_py',       label: 'google_calendar.py',    type: 'script', v: ['cortex'], desc: 'list, add, delete, rsvp, calendars [--private]' },
  { id: 'notion_py',         label: 'notion.py',             type: 'script', v: ['cortex'], desc: 'query, search, add-task, add-note, add-activity' },
  { id: 'notion2email_py',   label: 'notion_to_email.py',    type: 'script', v: ['cortex'], desc: 'Notion page -> HTML email' },
  { id: 'cloudflare_py',     label: 'cloudflare.py',         type: 'script', v: ['cortex'], desc: 'overview, detail, cache, purge' },
  { id: 'seo_report_py',     label: 'seo_report.py',         type: 'script', v: ['cortex'], desc: 'raport SEO -> Notion' },
  { id: 'health_check_py',   label: 'health_check.py',       type: 'script', v: ['cortex'], desc: 'smoke test integracji' },
  { id: 'fireflies_py',      label: 'fireflies_to_notion.py',type: 'script', v: ['cortex'], desc: 'transkrypcje -> Notion' },
  { id: 'google_ads_py',     label: 'google_ads.py',         type: 'script', v: ['cortex'], desc: '19 komend: kampanie, KP, forecast' },
  { id: 'ga4_py',            label: 'ga4.py',                type: 'script', v: ['cortex'], desc: 'dane GA4' },
  { id: 'search_console_py', label: 'search_console.py',     type: 'script', v: ['cortex'], desc: 'pozycje, kliki GSC' },
  { id: 'deploy_ftp_sh',     label: 'deploy_ftp.sh',         type: 'script', v: ['cortex'], desc: 'deploy FTP stron' },
  { id: 'update_context_py', label: 'update_context.py',     type: 'script', v: ['cortex'], desc: 'generuje context.md' },
  { id: 'smoke_test_py',     label: 'smoke_test.py',         type: 'script', v: ['cortex'], desc: 'test Notion + Gmail' },
  { id: 'google_admin_py',  label: 'google_admin.py',       type: 'script', v: ['cortex'], desc: 'users, groups, aliases, security, report — Google Workspace' },
  { id: 'indexing_py',      label: 'indexing.py',           type: 'script', v: ['cortex'], desc: 'submit, inspect, sitemap — Google Indexing API' },
  { id: 'check_treningi_py',label: 'check_treningi.py',     type: 'script', v: ['cortex'], desc: 'podsumowanie treningów z Notion' },
  { id: 'notion_replace_py',label: 'notion_replace_page.py',type: 'script', v: ['cortex'], desc: 'kasuje i odtwarza strone Notion (masowa edycja)' },
  { id: 'update_supl_py',   label: 'update_suplementy.py',  type: 'script', v: ['cortex'], desc: 'aktualizacja bazy suplementów' },
  { id: 'system_audit_py',  label: 'system_audit.py',       type: 'script', v: ['cortex'], desc: 'summary/errors/tail/run/briefing — czyta BigQuery pipeline_logs. Feed sekcji "🤖 Systemy w nocy" w briefingu.' },

  // Cortex v2 migration (2026-04-18) — auto-source-of-truth dla infry
  { id: 'infra_snapshot_py', label: 'infra_snapshot.py',    type: 'script', v: ['cortex'], desc: 'Generuje LIVE mapę infry (gcloud scheduler/run/functions + pm2 + systemd) do _infra_live.md. Odpalany przez update_context.py.' },
  { id: 'drift_linter_py',   label: 'drift_linter.py',      type: 'script', v: ['cortex'], desc: 'Wykrywa rozjazdy: skrypty w docs vs scripts/, memory refs, live vs mapy tekstowe, skills bez SKILL.md, stale files.' },
  { id: 'infra_live_md',     label: '_infra_live.md',       type: 'core',   v: ['cortex'], desc: 'LIVE snapshot infry — auto-generowany, wklejany do context.md każdej sesji. Single source of truth dla GCP+Mikrus+lokalnych automatów.' },
  { id: 'cortex_routing_md', label: 'cortex_routing.md',    type: 'core',   v: ['cortex'], desc: 'Mapa "Adi mówi X → Claude robi Y". Routing fraz naturalnych na konkretne akcje i skrypty.' },

  // Timers
  { id: 'timer_context',   label: 'cortex-context (07:00)',type: 'timer', v: ['cortex'], desc: 'systemd -> update_context.py' },
  { id: 'timer_smoke',     label: 'cortex-smoke (07:10)',  type: 'timer', v: ['cortex'], desc: 'systemd -> smoke_test.py' },
  { id: 'timer_seo',       label: 'cortex-seo (pon 07:15)',type: 'timer', v: ['cortex'], desc: 'systemd -> seo_report.py' },
  { id: 'timer_claude_backup', label: 'cortex-claude-backup (22:00)', type: 'timer', v: ['cortex'], desc: 'systemd -> claude_config_backup.py --gcs (fallback po EOD)' },

  // APIs
  { id: 'gmail_api',       label: 'Gmail API',             type: 'api', v: ['cortex'], desc: 'OAuth, email ops' },
  { id: 'calendar_api',    label: 'Google Calendar API',   type: 'api', v: ['cortex'], desc: 'OAuth, events' },
  { id: 'notion_api_firm', label: 'Notion API (firmowe)',   type: 'api', v: ['cortex'], desc: 'NOTION_TOKEN_FIRMOWE, 20 baz' },
  { id: 'notion_api_priv', label: 'Notion API (prywatne)', type: 'api', v: ['cortex'], desc: 'NOTION_TOKEN_PRYWATNE, 12 baz' },
  { id: 'cloudflare_api',  label: 'Cloudflare API',        type: 'api', v: ['cortex'], desc: 'cache, purge, analytics' },
  { id: 'openai_api',      label: 'OpenAI API',            type: 'api', v: ['cortex'], desc: 'GPT-4o, Whisper' },
  { id: 'fireflies_api',   label: 'Fireflies API',         type: 'api', v: ['cortex'], desc: 'transkrypcje spotkań' },
  { id: 'google_ads_api',  label: 'Google Ads API',        type: 'api', v: ['cortex'], desc: 'Basic Access, MCC' },
  { id: 'ga4_api',         label: 'GA4 API',               type: 'api', v: ['cortex'], desc: 'analytics 4' },
  { id: 'gsc_api',         label: 'Search Console API',    type: 'api', v: ['cortex'], desc: 'pozycje, kliki' },
  { id: 'psi_api',         label: 'PageSpeed Insights',    type: 'api', v: ['cortex'], desc: 'GOOGLE_API_KEY' },
  { id: 'gdrive_api',      label: 'Google Drive API',      type: 'api', v: ['cortex'], desc: 'OAuth, backup' },
  { id: 'dhosting_ftp',    label: 'dhosting FTP',          type: 'api', v: ['cortex'], desc: 'FTP deploy' },
  { id: 'supabase',        label: 'Supabase',              type: 'api', v: ['cortex'], desc: 'DB: PM, ZakupEX' },
  { id: 'apify',           label: 'Apify',                 type: 'api', v: ['cortex'], desc: 'scraping cen, Otodom' },
  { id: 'google_admin_api',label: 'Google Admin SDK',      type: 'api', v: ['cortex'], desc: 'users, groups, aliases — Workspace PEG' },
  { id: 'indexing_api',    label: 'Google Indexing API',   type: 'api', v: ['cortex'], desc: 'submit URLi do Google' },
  { id: 'mikrus_pg',       label: 'PostgreSQL (Mikrus)',   type: 'api', v: ['cortex'], desc: 'DB Janusz: messages_log, timecard_entries' },

  // MCP
  { id: 'mcp_chrome',      label: 'claude-in-chrome',      type: 'mcp', v: ['cortex'], desc: 'automatyzacja Chrome' },
  { id: 'mcp_canva',       label: 'Canva MCP',             type: 'mcp', v: ['cortex'], desc: 'tworzenie designów' },
  { id: 'mcp_notion_ai',   label: 'Notion (claude.ai)',    type: 'mcp', v: ['cortex'], desc: 'Notion z Claude.ai' },
  { id: 'mcp_notion_firm', label: 'notion-firmowe MCP',    type: 'mcp', v: ['cortex'], desc: 'API bazy firmowe' },
  { id: 'mcp_notion_priv', label: 'notion-prywatne MCP',   type: 'mcp', v: ['cortex'], desc: 'API bazy prywatne' },
  { id: 'mcp_fireflies',   label: 'Fireflies MCP',         type: 'mcp', v: ['cortex'], desc: 'transkrypcje' },
  { id: 'mcp_gmail',       label: 'Gmail MCP',             type: 'mcp', v: ['cortex'], desc: 'Gmail z Claude.ai' },
  { id: 'mcp_calendar',    label: 'Calendar MCP',          type: 'mcp', v: ['cortex'], desc: 'kalendarz z Claude.ai' },

  // Apps (z backendem, bazą, własną logiką)
  { id: 'app_pm',          label: 'PM',                    type: 'app', v: ['cortex'], desc: 'Pricing Manager — Next.js 16, Supabase, Apify — price.partnerexpert.work' },
  { id: 'app_zakupex',     label: 'ZakupEX',               type: 'app', v: ['cortex'], desc: 'System faktur — Next.js 16, Supabase, OCR GPT-4o. Cloud Run europe-west1, domena zakupex.partnerexpert.work (migrowane z Vercel 2026-04-13).' },
  { id: 'app_janusz',      label: 'Janusz',                type: 'app', v: ['cortex'], desc: 'PERSONA: WhatsApp bot zespołu PEG + PM obowiązki — Node.js, Baileys, GPT-4o-mini — Mikrus (🟢 live)' },
  { id: 'app_gustaw',      label: 'Gustaw',                type: 'app', v: ['cortex'], desc: 'PERSONA: WhatsApp asystent Adiego — Node.js, Baileys, GPT-4o + Gemini — Mikrus (🔴 czeka na SIM)' },

  // Strony WWW (statyczne / SSG / SPA bez własnego backendu)
  { id: 'www_indu',        label: 'IND.U',                 type: 'www', v: ['cortex'], desc: 'induapartamenty.pl — strona apartamentów IND.U, dhosting FTP, Meta Pixel 464727134708292' },
  { id: 'www_sunday',      label: 'Sunday',                type: 'www', v: ['cortex'], desc: 'sundayapartamenty.pl — strona apartamentów Sunday, dhosting FTP' },
  { id: 'www_peg',         label: 'PEG WWW',               type: 'www', v: ['cortex'], desc: 'partnerexpert.pl — strona korporacyjna PEG, dhosting FTP' },
  { id: 'www_muszla',      label: 'muszla.pl',             type: 'www', v: ['cortex'], desc: 'muszlakolobrzeg.pl — strona Muszli Kołobrzeg, Astro 5, React 19, Tailwind 4, Vercel' },
  { id: 'www_atlas',       label: 'Atlas',                 type: 'www', v: ['cortex'], desc: 'Atlas Cortexu — dashboard mapowy ekosystemu PEG, GitHub Pages (aszufel.github.io/atlas)' },
  { id: 'www_extranet',    label: 'Extranet PEG',          type: 'www', v: ['cortex'], desc: 'extranet.partnerexpert.work — wewnętrzny portal PEG, Next.js 16, Cloud Run europe-west1' },

  // Nowe skrypty (2026-04-11)
  { id: 'gbp_py',             label: 'gbp.py',               type: 'script', v: ['cortex'], desc: 'Google Business Profile — list, open, close, hours, reviews, reply. Aliasy: muszla, indu, sunday...' },
  { id: 'content_pipeline_py',label: 'content_pipeline.py',  type: 'script', v: ['cortex'], desc: 'Rolki + posty z podcastu Tamborskiego — Whisper, GPT-4o, ffmpeg, OpenCV. Zmigrowane na GCP Cloud Run Job 2026-04-12.' },
  { id: 'archiwista_sh',     label: 'archiwista.sh',        type: 'script', v: ['cortex'], desc: 'Backup PG + .env → strych.mikr.us + GCS' },

  // Automaty Mikrusa (tylko archiwista pozostal, reszta na GCP od 2026-04-12)
  { id: 'cron_archiwista',   label: 'archiwista (4:00)',     type: 'automat', v: ['cortex'], desc: '🟢 Backup PG + .env → strych.mikr.us + GCS, codziennie 4:00, retencja 30 dni. JEDYNY cron na Mikrusie.' },

  // Nowe API
  { id: 'gbp_api',           label: 'GBP API',               type: 'api', v: ['cortex'], desc: 'Google Business Profile — wizytówki, recenzje, godziny' },
  { id: 'fb_api',            label: 'Facebook API',           type: 'api', v: ['cortex'], desc: 'Page token Tamborski — auto-publish postów i rolek' },
  { id: 'strych',            label: 'strych.mikr.us',        type: 'hosting', v: ['cortex'], desc: 'Serwer backupowy Mikrusa — 683GB, SSH/SCP, darmowy' },

  // Repos
  { id: 'repo_cortex',     label: 'Cortex.git',            type: 'repo', v: ['cortex'], desc: 'System operacyjny AI — ~/Cortex + /home/cortex/ na Mikrusie' },
  { id: 'repo_pm',         label: 'PM.git',                type: 'repo', v: ['cortex'], desc: 'Next.js, Supabase' },
  { id: 'repo_zakupex',    label: 'Zakupex.git',           type: 'repo', v: ['cortex'], desc: 'Next.js, Supabase' },
  { id: 'repo_janusz',     label: 'Janusz.git',            type: 'repo', v: ['cortex'], desc: 'Node.js, Baileys, PostgreSQL' },
  { id: 'repo_gustaw',     label: 'Gustaw.git',            type: 'repo', v: ['cortex'], desc: 'Node.js, Baileys, GPT-4o — WhatsApp asystent Adiego' },
  { id: 'repo_muszla',     label: 'muszla.pl.git',         type: 'repo', v: ['cortex'], desc: 'Astro' },
  { id: 'repo_atlas',      label: 'atlas.git',             type: 'repo', v: ['cortex'], desc: 'Cytoscape.js — mapa ekosystemu PEG, hostowana na GitHub Pages' },

  // Hosting
  { id: 'vercel',          label: 'Vercel',                type: 'hosting', v: ['cortex'], desc: 'PM, muszla.pl. (ZakupEX migrowane do Cloud Run 2026-04-13, BOT Voice skasowane 2026-04-18.)' },
  { id: 'dhosting',        label: 'dhosting',              type: 'hosting', v: ['cortex'], desc: 'FTP: IND.U, Sunday, PEG, GEA. Crony PHP ZABLOKOWANE 2026-04-12 (migrowane na GCP Scheduler).' },
  { id: 'gcp',             label: 'GCP Cortex',            type: 'gcp', v: ['cortex'], desc: 'Project ai-council-487609, region europe-central2. Budget 50zł/mies (alerty 50/90/100%). Realny koszt ~10-12zł.' },
  { id: 'gcp_sm',          label: 'Secret Manager',        type: 'secret', v: ['cortex'], desc: '8 sekretów: notion-token-firmowe/prywatne, supabase-pm-key, supabase-zakupex-key, openai-api-key, cloudflare-api-token, cortex-api-key, google-oauth-token' },
  { id: 'gcp_bucket',      label: 'gs://peg-backups-cortex', type: 'bucket', v: ['cortex'], desc: 'Bucket GCS, lifecycle 30 dni. Foldery: notion/, supabase/, cloudflare/, claude-config/, mikrus/' },
  { id: 'gcp_ar',          label: 'Artifact Registry',     type: 'gcp', v: ['cortex'], desc: 'cortex-jobs/ — Docker images dla Cloud Run Jobs' },
  { id: 'gcp_uptime',      label: 'Uptime Check + Alert',  type: 'gcp', v: ['cortex'], desc: 'janusz-mikrus-health co 5min → /health. Alert email: Janusz DOWN po 60s.' },
  { id: 'gcp_bq',          label: 'BigQuery pipeline_logs', type: 'gcp', v: ['cortex'], desc: 'Dataset cortex_logs (EU), tabela pipeline_logs (partitioned by DAY, 30d retention). Centralny dziennik wszystkich apek PEG. Kolumny: created_at, app, level, source, event, message, meta (JSON), run_id. SA: pipeline-logger (zapis), cortex-backups (odczyt od 2026-04-21).' },

  // GCP Cloud Run Functions (4)
  { id: 'cr_notion_backup', label: 'notion-backup',        type: 'gcp', v: ['cortex'], desc: 'Cloud Run Function — 28 baz Notion → GCS' },
  { id: 'cr_supabase_backup', label: 'supabase-backup',    type: 'gcp', v: ['cortex'], desc: 'Cloud Run Function — PM + ZakupEX → GCS' },
  { id: 'cr_cloudflare_backup', label: 'cloudflare-backup',type: 'gcp', v: ['cortex'], desc: 'Cloud Run Function — 6 zon CF → GCS' },
  { id: 'cr_recenzent',    label: 'recenzent',             type: 'gcp', v: ['cortex'], desc: 'Cloud Run Function — Auto-odpowiedzi na recenzje GBP (5 obiektow PEG). GPT-4o-mini.' },
  { id: 'cr_health_check', label: 'health-check',          type: 'gcp', v: ['cortex'], desc: 'Cloud Function — Pinguje 7 apek PEG, alert WA DM przy UP↔DOWN, throttle 60 min. State w gs://peg-backups-cortex/health-check/.' },
  { id: 'cr_workspace_audit', label: 'workspace-audit',    type: 'gcp', v: ['cortex'], desc: 'Cloud Function — Audyt Google Workspace (2FA, nieaktywni, admini) → raport w Notion/email.' },
  { id: 'cr_indexing',     label: 'indexing-daily',        type: 'gcp', v: ['cortex'], desc: 'Cloud Function — Submit URL z sitemap (5 domen PEG) do Google Indexing API.' },
  { id: 'cr_zakupex_import', label: 'zakupex-auto-import', type: 'gcp', v: ['cortex'], desc: 'Cloud Function — OCR faktur z maila → Zakupex (codziennie 02:00).' },
  { id: 'cr_janusz_content', label: 'janusz-content-report', type: 'gcp', v: ['cortex'], desc: 'Cloud Function — Tygodniowy raport treści Janusza (wtorek 08:00).' },
  { id: 'cr_janusz_weekly', label: 'janusz-weekly-review', type: 'gcp', v: ['cortex'], desc: 'Cloud Function gen2 (2026-04-22) — raport chat loggingu Janusza (niedziela 20:00). Query cortex_logs.pipeline_logs source=chat, agreguje top no_tool_match/refused/tool_failed → WA DM do Adi.' },
  { id: 'cr_atlas_status', label: 'atlas-status',          type: 'gcp', v: ['cortex'], desc: 'Cloud Function — proxy dla gs://peg-backups-cortex/health-check/state.json (CORS) → atlas czyta live status 🟢/🔴. Utworzona 2026-04-17.' },

  // GCP Cloud Run Job
  { id: 'cr_content',      label: 'content-pipeline',      type: 'gcp', v: ['cortex'], desc: 'Cloud Run Job (Docker+ffmpeg+yt-dlp+opencv) — rolki podcast Tamborskiego' },

  // GCP Schedulers (8)
  { id: 'sch_notion',      label: 'notion-backup (4:00)',  type: 'sched', v: ['cortex'], desc: 'codziennie 4:00 → CR notion-backup' },
  { id: 'sch_supabase',    label: 'supabase-backup (4:30)',type: 'sched', v: ['cortex'], desc: 'codziennie 4:30 → CR supabase-backup' },
  { id: 'sch_cf',          label: 'cloudflare-backup (5:00)',type: 'sched', v: ['cortex'], desc: 'codziennie 5:00 → CR cloudflare-backup' },
  { id: 'sch_recenzent',   label: 'recenzent (co 4h)',     type: 'sched', v: ['cortex'], desc: 'co 4h → CR recenzent' },
  { id: 'sch_content',     label: 'content-pipeline (wt 3:00)',type: 'sched', v: ['cortex'], desc: 'wtorek 3:00 → CR Job content-pipeline' },
  { id: 'sch_pm_scan',     label: 'pm-auto-scan (23:00)',  type: 'sched', v: ['cortex'], desc: 'codziennie 23:00 → GET price.partnerexpert.work/api/cron/auto-scan' },
  { id: 'sch_pm_summary',  label: 'pm-summary (01:00)',    type: 'sched', v: ['cortex'], desc: 'codziennie 01:00 → GET .../generate-summary' },
  { id: 'sch_pm_retry',    label: 'pm-retry (06:00)',      type: 'sched', v: ['cortex'], desc: 'codziennie 06:00 → GET .../retry-apify-runs' },
  { id: 'sch_health_check', label: 'health-check (co 15 min)', type: 'sched', v: ['cortex'], desc: 'co 15 min → CR health-check (ping 7 apek PEG)' },
  { id: 'sch_health_digest', label: 'health-digest (08:00)', type: 'sched', v: ['cortex'], desc: 'codziennie 08:00 → CR health-check (digest 24h)' },
  { id: 'sch_workspace_audit', label: 'workspace-audit (mc)', type: 'sched', v: ['cortex'], desc: 'ostatni piątek mc 07:00 → CR workspace-audit' },
  { id: 'sch_indexing',    label: 'indexing-daily (02:00)', type: 'sched', v: ['cortex'], desc: 'codziennie 02:00 → CR indexing-daily' },
  { id: 'sch_zakupex_import', label: 'zakupex-import (02:00)', type: 'sched', v: ['cortex'], desc: 'codziennie 02:00 → CR zakupex-auto-import' },
  { id: 'sch_janusz_content', label: 'janusz-content (wt 08:00)', type: 'sched', v: ['cortex'], desc: 'wtorek 08:00 → CR janusz-content-report' },
  { id: 'sch_janusz_weekly', label: 'janusz-weekly (nd 20:00)', type: 'sched', v: ['cortex'], desc: 'niedziela 20:00 → CR janusz-weekly-review (raport chat loggingu, pełny obraz)' },
  { id: 'sch_janusz_daily', label: 'janusz-daily (7:00)', type: 'sched', v: ['cortex'], desc: 'codziennie 7:00 → CR janusz-weekly-review?days=1 (raport z wczoraj + 1-3 najpilniejsze fixy)' },
  { id: 'sch_content_publish', label: 'content-publish (co 30m 8-22)', type: 'sched', v: ['cortex'], desc: 'co 30 min 8-22 → check publikacji FB rolek' },
  { id: 'mikrus',          label: 'Mikrus VPS',            type: 'hosting', v: ['cortex'], desc: 'leszek140, 1GB/10GB — Persony: Janusz (🟢), Gustaw (🔴). Jedyny automat: archiwista (4:00). Wszystkie inne crony migrowane na GCP 2026-04-12.' },
  { id: 'laptop',          label: 'Laptop (penguin)',       type: 'hosting', v: ['cortex'], desc: 'systemd timers, Cortex runtime — NIGDY crony produkcyjne' },

  // ========== BIZNESY VIEW (generowane z Notion Biznesy DB) ==========
  { id: 'str_food_hall_w_porcie', label: 'Food Hall w Porcie', type: 'strategia', v: ['biznesy'], desc: '⏸️ Pauza' },
  { id: 'str_noraco', label: 'Noraco', type: 'strategia', v: ['biznesy'], desc: '🟡 W trakcie' },
  { id: 'str_eba', label: 'Łeba', type: 'strategia', v: ['biznesy'], desc: '🔵 Umowa podpisana' },
  { id: 'biz_spot', label: 'Lobby Bar / Spot', type: 'punkt', v: ['biznesy','zespol'], desc: '🟢 aktywny' },
  { id: 'str_celka_500_apt', label: 'CELKA 500 APT', type: 'strategia', v: ['biznesy'], desc: '⏸️ Pauza' },
  { id: 'str_dzia_ka_w_grzybowie', label: 'Działka w Grzybowie', type: 'strategia', v: ['biznesy'], desc: '🟡 W trakcie' },
  { id: 'str_dzia_ka_przy_biedronce', label: 'Działka przy Biedronce', type: 'strategia', v: ['biznesy'], desc: '🟡 W trakcie' },
  { id: 'biz_indu', label: 'IND.U', type: 'punkt', v: ['biznesy','zespol'], desc: '🟢 aktywny' },
  { id: 'biz_per', label: 'PER', type: 'spolka', v: ['biznesy','zespol'], desc: '🟢 aktywny', parent: 'biz_peg' },
  { id: 'biz_muszla', label: 'Muszla', type: 'punkt', v: ['biznesy','zespol'], desc: '🟢 aktywny' },
  { id: 'biz_sunday', label: 'Sunday', type: 'punkt', v: ['biznesy','zespol'], desc: '🟢 aktywny' },
  { id: 'str_rogowo_60', label: 'Rogowo 60', type: 'strategia', v: ['biznesy'], desc: '🔵 Umowa podpisana' },
  { id: 'str_area_na_plazowej', label: 'Area na Plażowej', type: 'strategia', v: ['biznesy'], desc: '🟡 W trakcie' },
  { id: 'str_p50', label: 'P50', type: 'strategia', v: ['biznesy'], desc: '⏸️ Pauza' },
  { id: 'biz_peo', label: 'PEO', type: 'spolka', v: ['biznesy','zespol'], desc: '🟢 aktywny', parent: 'biz_peg' },
  { id: 'biz_sunset', label: 'Sunset', type: 'punkt', v: ['biznesy','zespol'], desc: '🟢 aktywny' },
  { id: 'biz_beachbox', label: 'Beach Box', type: 'punkt', v: ['biznesy','zespol'], desc: '🟢 aktywny' },
  { id: 'biz_pei', label: 'PEI', type: 'spolka', v: ['biznesy','zespol'], desc: '🟢 aktywny', parent: 'biz_peg' },
  { id: 'biz_peg', label: 'PEG (brand)', type: 'holding', v: ['biznesy','zespol'], desc: '🏷️ Brand parasolowy — NIE formalny holding' },
  { id: 'biz_gea', label: 'GEA Sea & Resort', type: 'punkt', v: ['biznesy','zespol'], desc: '🟢 aktywny' },
  { id: 'str_wild_pearl', label: 'Wild Pearl', type: 'strategia', v: ['biznesy'], desc: '🔵 Umowa podpisana' },

  // ========== ZESPÓŁ VIEW (generowane z Notion Pracownicy DB — tylko aktywni) ==========
  { id: 'p_buchuta_dorota', label: 'Buchuta Dorota', type: 'person_kierownicy', v: ['zespol'], desc: 'Kierownik baru' },
  { id: 'p_paula_ryzewska_korzen', label: 'Paula Ryżewska-Korzeń', type: 'person_specjalisci', v: ['zespol'], desc: 'Asystentka Sekretariatu' },
  { id: 'p_mateusz_kasprzak', label: 'Mateusz Kasprzak', type: 'person_pracownik_liniowy', v: ['zespol'], desc: 'Pracownik techniczny' },
  { id: 'p_daria_cieslak', label: 'Daria Cieślak', type: 'person_pracownik_liniowy', v: ['zespol'], desc: 'Pracownik kuchnia' },
  { id: 'p_tomasz_ciecwierski', label: 'Tomasz Ciećwierski', type: 'person_pracownik_liniowy', v: ['zespol'], desc: 'Pracownik techniczny' },
  { id: 'p_tetiana_poklad', label: 'Tetiana Poklad', type: 'person_pracownik_liniowy', v: ['zespol'], desc: 'Pracownik kuchnia' },
  { id: 'p_bogdan_be_ej', label: 'Bogdan Bełej', type: 'person_pracownik_liniowy', v: ['zespol'], desc: 'Pracownik techniczny' },
  { id: 'p_irmina_andrzejczuk', label: 'Irmina Andrzejczuk', type: 'person_zarzad', v: ['zespol'], desc: 'Dyrektor Zarządzający' },
  { id: 'p_katarzyna_matyjaszczyk', label: 'Katarzyna Matyjaszczyk', type: 'person_pracownik_liniowy', v: ['zespol'], desc: 'Pracownik kuchnia' },
  { id: 'p_krzysztof_seralis', label: 'Krzysztof Seralis', type: 'person_pracownik_liniowy', v: ['zespol'], desc: 'Pracownik kuchnia' },
  { id: 'p_julia_ma_ecka', label: 'Julia Małecka', type: 'person_pracownik_liniowy', v: ['zespol'], desc: 'Pracownik baru' },
  { id: 'p_anastasiia_makedonska', label: 'Anastasiia Makedonska', type: 'person_pracownik_liniowy', v: ['zespol'], desc: 'Pracownik baru' },
  { id: 'p_vasyl_kharskyy', label: 'Vasyl Kharskyy', type: 'person_pracownik_liniowy', v: ['zespol'], desc: 'Stróż' },
  { id: 'p_kaleta_kamil', label: 'Kaleta Kamil', type: 'person_pracownik_liniowy', v: ['zespol'], desc: 'Pracownik kuchnia' },
  { id: 'p_patrycja_kozbia', label: 'Patrycja Koźbiał', type: 'person_kierownicy', v: ['zespol'], desc: 'Kierownik baru' },
  { id: 'p_krystian_gaik', label: 'Krystian Gaik', type: 'person_pracownik_liniowy', v: ['zespol'], desc: 'Pracownik techniczny' },
  { id: 'p_urszula_kokoszczyk', label: 'Urszula Kokoszczyk', type: 'person_management', v: ['zespol'], desc: 'Dyrektor Zarządzający' },
  { id: 'p_bart_omiej_pietrasiak', label: 'Bartłomiej Pietrasiak', type: 'person_pracownik_liniowy', v: ['zespol'], desc: 'Pracownik techniczny' },
  { id: 'p_dorota_kornas', label: 'Dorota Kornas', type: 'person_specjalisci', v: ['zespol'], desc: 'Koordynator ds. Wynajmu Apartamentów' },
  { id: 'p_oliver_andrzejczuk', label: 'Oliver Andrzejczuk', type: 'person_zarzad', v: ['zespol'], desc: 'Członek zarządu' },
  { id: 'p_patrycja_furmankiewicz', label: 'Patrycja Furmankiewicz', type: 'person_management', v: ['zespol'], desc: 'Office Manager' },
  { id: 'p_maja_limanska', label: 'Maja Limańska', type: 'person_specjalisci', v: ['zespol'], desc: 'Specjalista ds. Rozliczeń' },
  { id: 'p_oliwia_wojcik', label: 'Oliwia Wójcik', type: 'person_kierownicy', v: ['zespol'], desc: 'Kierownik baru' },
  { id: 'p_iryna_shestakowa', label: 'Iryna Shestakowa', type: 'person_pracownik_liniowy', v: ['zespol'], desc: 'Pracownik kuchnia' },
  { id: 'p_tadeusz_zaborowski', label: 'Tadeusz Zaborowski', type: 'person_pracownik_liniowy', v: ['zespol'], desc: 'Pracownik techniczny' },
  { id: 'p_adrian_szufel', label: 'Adrian Szufel', type: 'person_zarzad', v: ['zespol'], desc: 'Członek zarządu' },
  { id: 'p_kamila_szczutkowska', label: 'Kamila Szczutkowska', type: 'person_specjalisci', v: ['zespol'], desc: 'Manager ds. Finansowych' },
  { id: 'p_beata_kasprzak', label: 'Beata Kasprzak', type: 'person_management', v: ['zespol'], desc: 'House Keeping Manager' },
  { id: 'p_viktoria_kulchytska_vouchko', label: 'Viktoria Kulchytska-Vouchko', type: 'person_pracownik_liniowy', v: ['zespol'], desc: 'Pracownik baru' },
  { id: 'p_inna_kvasnikowa', label: 'Inna Kvasnikowa', type: 'person_pracownik_liniowy', v: ['zespol'], desc: 'Pracownik kuchnia' },

];

const edges = [
  // ========== CORTEX EDGES ==========
  { source: 'update_context_py', target: 'context_md',      label: 'generates', v: ['cortex'] },
  // Repo Cortex — strukturalne edges (nie wszystkie skrypty, tylko główne kawałki)
  { source: 'repo_cortex', target: 'claude_md',     label: 'contains', v: ['cortex'] },
  { source: 'repo_cortex', target: 'context_md',    label: 'contains', v: ['cortex'] },
  { source: 'repo_cortex', target: 'env_file',      label: 'contains', v: ['cortex'] },
  { source: 'repo_cortex', target: 'knowledge_dir', label: 'contains', v: ['cortex'] },
  { source: 'repo_cortex', target: 'venv',          label: 'contains', v: ['cortex'] },
  // Knowledge dir — zawartość
  { source: 'knowledge_dir', target: 'notion_map',     label: 'mapa',    v: ['cortex'] },
  { source: 'knowledge_dir', target: 'ecosystem_map',  label: 'mapa',    v: ['cortex'] },
  { source: 'knowledge_dir', target: 'apps_map',      label: 'mapa',    v: ['cortex'] },
  { source: 'knowledge_dir', target: 'adi_psychology', label: 'profil',  v: ['cortex'] },
  { source: 'knowledge_dir', target: 'quotes_mazur',   label: 'cytaty',  v: ['cortex'] },
  // Atlas — osobny repo
  { source: 'mcp_chrome',     target: 'laptop',          label: 'browser',  v: ['cortex'] },
  { source: 'mcp_canva',      target: 'laptop',          label: 'MCP w chat', v: ['cortex'] },
  { source: 'mcp_notion_ai',  target: 'notion_api_firm', label: 'proxies',  v: ['cortex'] },
  { source: 'mcp_notion_ai',  target: 'notion_api_priv', label: 'proxies',  v: ['cortex'] },
  { source: 'gmail_py',          target: 'gmail_api',       label: 'OAuth',       v: ['cortex'] },
  { source: 'calendar_py',       target: 'calendar_api',    label: 'OAuth',       v: ['cortex'] },
  { source: 'notion_py',         target: 'notion_api_firm', label: 'token',       v: ['cortex'] },
  { source: 'notion_py',         target: 'notion_api_priv', label: 'token',       v: ['cortex'] },
  { source: 'notion2email_py',   target: 'notion_api_firm', label: 'read',        v: ['cortex'] },
  { source: 'notion2email_py',   target: 'gmail_api',       label: 'draft/send',  v: ['cortex'] },
  { source: 'cloudflare_py',     target: 'cloudflare_api',  label: 'token',       v: ['cortex'] },
  { source: 'seo_report_py',     target: 'cloudflare_api',  label: 'analytics',   v: ['cortex'] },
  { source: 'seo_report_py',     target: 'psi_api',         label: 'scores',      v: ['cortex'] },
  { source: 'seo_report_py',     target: 'notion_api_firm', label: 'write',       v: ['cortex'] },
  { source: 'health_check_py',   target: 'notion_api_firm', label: 'smoke',       v: ['cortex'] },
  { source: 'health_check_py',   target: 'gmail_api',       label: 'smoke',       v: ['cortex'] },
  { source: 'fireflies_py',      target: 'fireflies_api',   label: 'transcripts', v: ['cortex'] },
  { source: 'fireflies_py',      target: 'openai_api',      label: 'summarize',   v: ['cortex'] },
  { source: 'fireflies_py',      target: 'notion_api_firm', label: 'write',       v: ['cortex'] },
  { source: 'google_ads_py',     target: 'google_ads_api',  label: 'campaigns',   v: ['cortex'] },
  { source: 'ga4_py',            target: 'ga4_api',         label: 'analytics',   v: ['cortex'] },
  { source: 'search_console_py', target: 'gsc_api',         label: 'positions',   v: ['cortex'] },
  { source: 'deploy_ftp_sh',     target: 'dhosting_ftp',    label: 'FTP push',    v: ['cortex'] },
  { source: 'update_context_py', target: 'notion_api_firm', label: 'read',        v: ['cortex'] },
  { source: 'update_context_py', target: 'notion_api_priv', label: 'read',        v: ['cortex'] },
  { source: 'update_context_py', target: 'gmail_api',       label: 'inbox',       v: ['cortex'] },
  { source: 'update_context_py', target: 'calendar_api',    label: 'events',      v: ['cortex'] },
  { source: 'smoke_test_py',     target: 'notion_api_firm', label: 'test',        v: ['cortex'] },
  { source: 'smoke_test_py',     target: 'gmail_api',       label: 'test',        v: ['cortex'] },
  { source: 'google_admin_py',  target: 'google_admin_api',label: 'SDK',         v: ['cortex'] },
  { source: 'indexing_py',      target: 'indexing_api',    label: 'submit',      v: ['cortex'] },
  { source: 'app_janusz',  target: 'mikrus',           label: 'deploy',   v: ['cortex'] },
  { source: 'repo_gustaw', target: 'app_gustaw',       label: 'builds',   v: ['cortex'] },
  { source: 'timer_context', target: 'update_context_py', label: 'triggers', v: ['cortex'] },
  { source: 'timer_smoke',   target: 'smoke_test_py',     label: 'triggers', v: ['cortex'] },
  { source: 'timer_seo',     target: 'seo_report_py',     label: 'triggers', v: ['cortex'] },
  { source: 'timer_claude_backup', target: 'gcp_bucket', label: 'upload ~/.claude/', v: ['cortex'] },
  { source: 'mcp_notion_firm', target: 'notion_api_firm', label: 'proxies', v: ['cortex'] },
  { source: 'mcp_notion_priv', target: 'notion_api_priv', label: 'proxies', v: ['cortex'] },
  { source: 'mcp_gmail',       target: 'gmail_api',       label: 'proxies', v: ['cortex'] },
  { source: 'mcp_calendar',    target: 'calendar_api',    label: 'proxies', v: ['cortex'] },
  { source: 'mcp_fireflies',   target: 'fireflies_api',   label: 'proxies', v: ['cortex'] },
  { source: 'app_pm',       target: 'supabase',    label: 'DB cen',     v: ['cortex'] },
  { source: 'app_pm',       target: 'openai_api',  label: 'summaries',  v: ['cortex'] },
  { source: 'app_pm',       target: 'apify',       label: 'scraping',   v: ['cortex'] },
  { source: 'app_zakupex',  target: 'supabase',    label: 'DB faktur',  v: ['cortex'] },
  { source: 'app_janusz',   target: 'mikrus_pg',   label: 'messages+timecard', v: ['cortex'] },
  { source: 'app_janusz',   target: 'notion_api_firm', label: 'Wiki',   v: ['cortex'] },
  { source: 'app_janusz',   target: 'openai_api',  label: 'GPT',        v: ['cortex'] },
  { source: 'app_gustaw',   target: 'openai_api',  label: 'GPT/Gemini', v: ['cortex'] },
  { source: 'app_gustaw',   target: 'notion_api_firm', label: 'sync',  v: ['cortex'] },
  { source: 'repo_pm',       target: 'app_pm',       label: 'builds', v: ['cortex'] },
  { source: 'repo_zakupex',  target: 'app_zakupex',  label: 'builds', v: ['cortex'] },
  { source: 'repo_janusz',   target: 'app_janusz',   label: 'builds', v: ['cortex'] },
  { source: 'repo_muszla',   target: 'www_muszla',   label: 'builds', v: ['cortex'] },
  { source: 'repo_atlas',    target: 'www_atlas',    label: 'builds', v: ['cortex'] },
  { source: 'app_pm',      target: 'vercel',  label: 'deploy', v: ['cortex'] },
  { source: 'app_zakupex', target: 'gcp',     label: 'deploy (europe-west1)', v: ['cortex'] },
  { source: 'www_muszla',  target: 'vercel',  label: 'deploy', v: ['cortex'] },
  { source: 'www_atlas',   target: 'cr_atlas_status', label: 'status API', v: ['cortex'] },
  { source: 'deploy_ftp_sh', target: 'www_indu',   label: 'deploy', v: ['cortex'] },
  { source: 'deploy_ftp_sh', target: 'www_sunday', label: 'deploy', v: ['cortex'] },
  { source: 'deploy_ftp_sh', target: 'www_peg',    label: 'deploy', v: ['cortex'] },
  { source: 'www_indu',    target: 'dhosting', label: 'hosted', v: ['cortex'] },
  { source: 'www_sunday',  target: 'dhosting', label: 'hosted', v: ['cortex'] },
  { source: 'www_peg',     target: 'dhosting', label: 'hosted', v: ['cortex'] },
  { source: 'www_extranet', target: 'gcp', label: 'Cloud Run (europe-west1)', v: ['cortex'] },
  { source: 'update_context_py', target: 'infra_snapshot_py', label: 'triggers', v: ['cortex'] },
  { source: 'infra_snapshot_py', target: 'infra_live_md', label: 'generates', v: ['cortex'] },
  { source: 'infra_live_md', target: 'context_md', label: 'included', v: ['cortex'] },
  { source: 'deploy_ftp_sh', target: 'dhosting', label: 'FTP',  v: ['cortex'] },
  { source: 'laptop', target: 'timer_context', label: 'runs', v: ['cortex'] },
  { source: 'laptop', target: 'timer_smoke',   label: 'runs', v: ['cortex'] },
  { source: 'laptop', target: 'timer_seo',     label: 'runs', v: ['cortex'] },
  { source: 'laptop', target: 'timer_claude_backup', label: 'runs', v: ['cortex'] },

  // Nowe skrypty → repo
  { source: 'gbp_py',             target: 'gbp_api',       label: 'OAuth',      v: ['cortex'] },
  { source: 'content_pipeline_py',target: 'openai_api',     label: 'Whisper+GPT',v: ['cortex'] },
  { source: 'content_pipeline_py',target: 'fb_api',         label: 'publish',    v: ['cortex'] },
  { source: 'check_treningi_py', target: 'notion_api_priv',label: 'read',       v: ['cortex'] },
  { source: 'update_supl_py',    target: 'notion_api_priv',label: 'write',      v: ['cortex'] },
  { source: 'notion_replace_py', target: 'notion_api_firm',label: 'replace',    v: ['cortex'] },
  { source: 'seo_report_py',     target: 'gsc_api',        label: 'positions',  v: ['cortex'] },
  { source: 'seo_report_py',     target: 'ga4_api',        label: 'analytics',  v: ['cortex'] },
  // Archiwista (jedyny cron na Mikrusie)
  { source: 'cron_archiwista',    target: 'archiwista_sh',    label: 'triggers', v: ['cortex'] },
  { source: 'mikrus', target: 'cron_archiwista', label: 'cron', v: ['cortex'] },
  { source: 'archiwista_sh', target: 'strych',     label: 'backup',  v: ['cortex'] },
  { source: 'archiwista_sh', target: 'gcp_bucket', label: 'backup 2/2', v: ['cortex'] },
  { source: 'archiwista_sh', target: 'mikrus_pg',  label: 'pg_dump', v: ['cortex'] },
  // Persony → Mikrus
  { source: 'app_gustaw', target: 'mikrus', label: 'deploy', v: ['cortex'] },
  // GCP — struktura
  { source: 'gcp', target: 'gcp_sm',     label: 'has', v: ['cortex'] },
  { source: 'gcp', target: 'gcp_bucket', label: 'has', v: ['cortex'] },
  { source: 'gcp', target: 'gcp_ar',     label: 'has', v: ['cortex'] },
  { source: 'gcp', target: 'gcp_uptime', label: 'has', v: ['cortex'] },
  { source: 'gcp', target: 'cr_notion_backup',    label: 'runs', v: ['cortex'] },
  { source: 'gcp', target: 'cr_supabase_backup',  label: 'runs', v: ['cortex'] },
  { source: 'gcp', target: 'cr_cloudflare_backup',label: 'runs', v: ['cortex'] },
  { source: 'gcp', target: 'cr_recenzent',        label: 'runs', v: ['cortex'] },
  { source: 'gcp', target: 'cr_content',          label: 'runs Job', v: ['cortex'] },
  // Schedulery → CR
  { source: 'sch_notion',     target: 'cr_notion_backup',    label: 'triggers', v: ['cortex'] },
  { source: 'sch_supabase',   target: 'cr_supabase_backup',  label: 'triggers', v: ['cortex'] },
  { source: 'sch_cf',         target: 'cr_cloudflare_backup',label: 'triggers', v: ['cortex'] },
  { source: 'sch_recenzent',  target: 'cr_recenzent',        label: 'triggers', v: ['cortex'] },
  { source: 'sch_content',    target: 'cr_content',          label: 'triggers', v: ['cortex'] },
  { source: 'sch_pm_scan',    target: 'app_pm',              label: 'HTTP GET', v: ['cortex'] },
  { source: 'sch_pm_summary', target: 'app_pm',              label: 'HTTP GET', v: ['cortex'] },
  { source: 'sch_pm_retry',   target: 'app_pm',              label: 'HTTP GET', v: ['cortex'] },
  // GCP → secret consumers
  { source: 'gcp_sm', target: 'cr_notion_backup',     label: 'secrets', v: ['cortex'] },
  { source: 'gcp_sm', target: 'cr_supabase_backup',   label: 'secrets', v: ['cortex'] },
  { source: 'gcp_sm', target: 'cr_cloudflare_backup', label: 'secrets', v: ['cortex'] },
  { source: 'gcp_sm', target: 'cr_recenzent',         label: 'secrets', v: ['cortex'] },
  { source: 'gcp_sm', target: 'cr_content',           label: 'secrets', v: ['cortex'] },
  // CR Functions → APIs
  { source: 'cr_notion_backup',    target: 'notion_api_firm', label: 'backup', v: ['cortex'] },
  { source: 'cr_notion_backup',    target: 'notion_api_priv', label: 'backup', v: ['cortex'] },
  { source: 'cr_notion_backup',    target: 'gcp_bucket',      label: 'write',  v: ['cortex'] },
  { source: 'cr_supabase_backup',  target: 'supabase',        label: 'dump',   v: ['cortex'] },
  { source: 'cr_supabase_backup',  target: 'gcp_bucket',      label: 'write',  v: ['cortex'] },
  { source: 'cr_cloudflare_backup',target: 'cloudflare_api',  label: 'dump',   v: ['cortex'] },
  { source: 'cr_cloudflare_backup',target: 'gcp_bucket',      label: 'write',  v: ['cortex'] },
  { source: 'cr_recenzent',        target: 'gbp_api',         label: 'reviews',v: ['cortex'] },
  { source: 'cr_recenzent',        target: 'openai_api',      label: 'GPT reply', v: ['cortex'] },
  { source: 'cr_recenzent',        target: 'app_janusz',      label: 'raport WA', v: ['cortex'] },
  { source: 'cr_content',          target: 'openai_api',      label: 'Whisper+GPT', v: ['cortex'] },
  { source: 'cr_content',          target: 'gdrive_api',      label: 'rolki Shared Drive', v: ['cortex'] },
  { source: 'cr_content',          target: 'notion_api_firm', label: 'Social Planner', v: ['cortex'] },
  { source: 'gcp_ar',              target: 'cr_content',      label: 'Docker image', v: ['cortex'] },
  // Uptime monitoring
  { source: 'gcp_uptime', target: 'app_janusz', label: 'health check', v: ['cortex'] },
  // BigQuery pipeline_logs (2026-04-17, rozszerzone 2026-04-20 o 6 apek)
  { source: 'gcp', target: 'gcp_bq', label: 'has', v: ['cortex'] },
  { source: 'app_pm', target: 'gcp_bq', label: 'pipeline logs', v: ['cortex'] },
  { source: 'app_zakupex', target: 'gcp_bq', label: 'pipeline logs', v: ['cortex'] },
  { source: 'app_janusz', target: 'gcp_bq', label: 'pipeline logs', v: ['cortex'] },
  { source: 'cr_recenzent', target: 'gcp_bq', label: 'pipeline logs', v: ['cortex'] },
  { source: 'cr_health_check', target: 'gcp_bq', label: 'pipeline logs', v: ['cortex'] },
  { source: 'cr_notion_backup', target: 'gcp_bq', label: 'pipeline logs', v: ['cortex'] },
  { source: 'cr_supabase_backup', target: 'gcp_bq', label: 'pipeline logs', v: ['cortex'] },
  { source: 'cr_cloudflare_backup', target: 'gcp_bq', label: 'pipeline logs', v: ['cortex'] },
  { source: 'gcp_bq', target: 'system_audit_py', label: 'query', v: ['cortex'] },
  { source: 'system_audit_py', target: 'update_context_py', label: 'feed briefing', v: ['cortex'] },
  // Brakujące Scheduler + Cloud Run (2026-04-17)
  { source: 'gcp', target: 'cr_health_check', label: 'runs', v: ['cortex'] },
  { source: 'gcp', target: 'cr_workspace_audit', label: 'runs', v: ['cortex'] },
  { source: 'gcp', target: 'cr_indexing', label: 'runs', v: ['cortex'] },
  { source: 'gcp', target: 'cr_zakupex_import', label: 'runs', v: ['cortex'] },
  { source: 'gcp', target: 'cr_janusz_content', label: 'runs', v: ['cortex'] },
  { source: 'gcp', target: 'cr_janusz_weekly', label: 'runs', v: ['cortex'] },
  { source: 'sch_health_check', target: 'cr_health_check', label: 'triggers', v: ['cortex'] },
  { source: 'sch_health_digest', target: 'cr_health_check', label: 'triggers', v: ['cortex'] },
  { source: 'sch_workspace_audit', target: 'cr_workspace_audit', label: 'triggers', v: ['cortex'] },
  { source: 'sch_indexing', target: 'cr_indexing', label: 'triggers', v: ['cortex'] },
  { source: 'sch_zakupex_import', target: 'cr_zakupex_import', label: 'triggers', v: ['cortex'] },
  { source: 'sch_janusz_content', target: 'cr_janusz_content', label: 'triggers', v: ['cortex'] },
  { source: 'sch_janusz_weekly', target: 'cr_janusz_weekly', label: 'triggers', v: ['cortex'] },
  { source: 'sch_janusz_daily', target: 'cr_janusz_weekly', label: 'triggers (daily)', v: ['cortex'] },
  { source: 'sch_content_publish', target: 'cr_content', label: 'triggers', v: ['cortex'] },
  { source: 'cr_health_check', target: 'app_pm', label: 'pings', v: ['cortex'] },
  { source: 'cr_health_check', target: 'app_zakupex', label: 'pings', v: ['cortex'] },
  { source: 'cr_health_check', target: 'app_janusz', label: 'pings + WA alert', v: ['cortex'] },
  { source: 'cr_indexing', target: 'indexing_api', label: 'submit URLs', v: ['cortex'] },
  { source: 'cr_workspace_audit', target: 'google_admin_api', label: 'audit', v: ['cortex'] },
  { source: 'cr_zakupex_import', target: 'app_zakupex', label: 'imports', v: ['cortex'] },
  { source: 'cr_zakupex_import', target: 'gmail_api', label: 'reads faktury', v: ['cortex'] },
  { source: 'cr_janusz_content', target: 'app_janusz', label: 'reports', v: ['cortex'] },
  { source: 'cr_janusz_weekly', target: 'app_janusz', label: 'WA raport', v: ['cortex'] },
  { source: 'gcp_bq', target: 'cr_janusz_weekly', label: 'chat logs read', v: ['cortex'] },
  { source: 'cr_health_check', target: 'gcp_bucket', label: 'state.json', v: ['cortex'] },
  // Persony → Mikrus
  { source: 'app_gustaw', target: 'mikrus', label: 'deploy', v: ['cortex'] },

  // ========== BIZNESY EDGES (generowane z Notion) ==========
  // PEG to brand parasolowy (compound parent). Prawdziwa zależność: PEI ma 80% udziałów w PEO i PER
  { source: 'biz_pei', target: 'biz_peo', label: '80% udziałów', v: ['biznesy','zespol'] },
  { source: 'biz_pei', target: 'biz_per', label: '80% udziałów', v: ['biznesy','zespol'] },
  { source: 'biz_peo', target: 'biz_indu',    label: '', v: ['biznesy','zespol'] },
  { source: 'biz_peo', target: 'biz_sunday',  label: '', v: ['biznesy','zespol'] },
  { source: 'biz_peo', target: 'biz_gea',     label: '', v: ['biznesy','zespol'] },
  { source: 'biz_peo', target: 'biz_spot',    label: '', v: ['biznesy','zespol'] },
  { source: 'biz_per', target: 'biz_muszla',  label: '', v: ['biznesy','zespol'] },
  { source: 'biz_per', target: 'biz_beachbox',label: '', v: ['biznesy','zespol'] },
  { source: 'biz_per', target: 'biz_sunset',  label: '', v: ['biznesy','zespol'] },
  { source: 'biz_pei', target: 'str_food_hall_w_porcie', label: 'Pauza', v: ['biznesy'] },
  { source: 'biz_pei', target: 'str_noraco', label: 'W trakcie', v: ['biznesy'] },
  { source: 'biz_pei', target: 'str_eba', label: 'Umowa podpisana', v: ['biznesy'] },
  { source: 'biz_pei', target: 'str_celka_500_apt', label: 'Pauza', v: ['biznesy'] },
  { source: 'biz_pei', target: 'str_dzia_ka_w_grzybowie', label: 'W trakcie', v: ['biznesy'] },
  { source: 'biz_pei', target: 'str_dzia_ka_przy_biedronce', label: 'W trakcie', v: ['biznesy'] },
  { source: 'biz_pei', target: 'str_rogowo_60', label: 'Umowa podpisana', v: ['biznesy'] },
  { source: 'biz_pei', target: 'str_area_na_plazowej', label: 'W trakcie', v: ['biznesy'] },
  { source: 'biz_pei', target: 'str_p50', label: 'Pauza', v: ['biznesy'] },
  { source: 'biz_pei', target: 'str_wild_pearl', label: 'Umowa podpisana', v: ['biznesy'] },

  // ========== ZESPÓŁ EDGES (generowane z Notion — pracownik → punkty) ==========
  { source: 'p_buchuta_dorota', target: 'biz_per', label: '', v: ['zespol'] },
  { source: 'p_buchuta_dorota', target: 'biz_sunset', label: '', v: ['zespol'] },
  { source: 'p_paula_ryzewska_korzen', target: 'biz_pei', label: '', v: ['zespol'] },
  { source: 'p_paula_ryzewska_korzen', target: 'biz_per', label: '', v: ['zespol'] },
  { source: 'p_paula_ryzewska_korzen', target: 'biz_peo', label: '', v: ['zespol'] },
  { source: 'p_paula_ryzewska_korzen', target: 'biz_indu', label: '', v: ['zespol'] },
  { source: 'p_mateusz_kasprzak', target: 'biz_peo', label: '', v: ['zespol'] },
  { source: 'p_mateusz_kasprzak', target: 'biz_indu', label: '', v: ['zespol'] },
  { source: 'p_mateusz_kasprzak', target: 'biz_sunday', label: '', v: ['zespol'] },
  { source: 'p_daria_cieslak', target: 'biz_peo', label: '', v: ['zespol'] },
  { source: 'p_daria_cieslak', target: 'biz_spot', label: '', v: ['zespol'] },
  { source: 'p_tomasz_ciecwierski', target: 'biz_per', label: '', v: ['zespol'] },
  { source: 'p_tetiana_poklad', target: 'biz_per', label: '', v: ['zespol'] },
  { source: 'p_tetiana_poklad', target: 'biz_beachbox', label: '', v: ['zespol'] },
  { source: 'p_bogdan_be_ej', target: 'biz_per', label: '', v: ['zespol'] },
  { source: 'p_irmina_andrzejczuk', target: 'biz_per', label: '', v: ['zespol'] },
  { source: 'p_irmina_andrzejczuk', target: 'biz_beachbox', label: '', v: ['zespol'] },
  { source: 'p_katarzyna_matyjaszczyk', target: 'biz_peo', label: '', v: ['zespol'] },
  { source: 'p_katarzyna_matyjaszczyk', target: 'biz_spot', label: '', v: ['zespol'] },
  { source: 'p_krzysztof_seralis', target: 'biz_per', label: '', v: ['zespol'] },
  { source: 'p_krzysztof_seralis', target: 'biz_muszla', label: '', v: ['zespol'] },
  { source: 'p_julia_ma_ecka', target: 'biz_per', label: '', v: ['zespol'] },
  { source: 'p_julia_ma_ecka', target: 'biz_muszla', label: '', v: ['zespol'] },
  { source: 'p_anastasiia_makedonska', target: 'biz_per', label: '', v: ['zespol'] },
  { source: 'p_anastasiia_makedonska', target: 'biz_beachbox', label: '', v: ['zespol'] },
  { source: 'p_vasyl_kharskyy', target: 'biz_per', label: '', v: ['zespol'] },
  { source: 'p_vasyl_kharskyy', target: 'biz_beachbox', label: '', v: ['zespol'] },
  { source: 'p_kaleta_kamil', target: 'biz_per', label: '', v: ['zespol'] },
  { source: 'p_kaleta_kamil', target: 'biz_muszla', label: '', v: ['zespol'] },
  { source: 'p_patrycja_kozbia', target: 'biz_per', label: '', v: ['zespol'] },
  { source: 'p_patrycja_kozbia', target: 'biz_muszla', label: '', v: ['zespol'] },
  { source: 'p_krystian_gaik', target: 'biz_per', label: '', v: ['zespol'] },
  { source: 'p_urszula_kokoszczyk', target: 'biz_per', label: '', v: ['zespol'] },
  { source: 'p_urszula_kokoszczyk', target: 'biz_muszla', label: '', v: ['zespol'] },
  { source: 'p_bart_omiej_pietrasiak', target: 'biz_per', label: '', v: ['zespol'] },
  { source: 'p_bart_omiej_pietrasiak', target: 'biz_peo', label: '', v: ['zespol'] },
  { source: 'p_dorota_kornas', target: 'biz_peo', label: '', v: ['zespol'] },
  { source: 'p_dorota_kornas', target: 'biz_indu', label: '', v: ['zespol'] },
  { source: 'p_dorota_kornas', target: 'biz_sunday', label: '', v: ['zespol'] },
  { source: 'p_oliver_andrzejczuk', target: 'biz_peg', label: '', v: ['zespol'] },
  { source: 'p_patrycja_furmankiewicz', target: 'biz_peo', label: '', v: ['zespol'] },
  { source: 'p_patrycja_furmankiewicz', target: 'biz_indu', label: '', v: ['zespol'] },
  { source: 'p_patrycja_furmankiewicz', target: 'biz_sunday', label: '', v: ['zespol'] },
  { source: 'p_maja_limanska', target: 'biz_per', label: '', v: ['zespol'] },
  { source: 'p_maja_limanska', target: 'biz_peo', label: '', v: ['zespol'] },
  { source: 'p_maja_limanska', target: 'biz_sunday', label: '', v: ['zespol'] },
  { source: 'p_maja_limanska', target: 'biz_indu', label: '', v: ['zespol'] },
  { source: 'p_oliwia_wojcik', target: 'biz_per', label: '', v: ['zespol'] },
  { source: 'p_oliwia_wojcik', target: 'biz_beachbox', label: '', v: ['zespol'] },
  { source: 'p_iryna_shestakowa', target: 'biz_per', label: '', v: ['zespol'] },
  { source: 'p_iryna_shestakowa', target: 'biz_beachbox', label: '', v: ['zespol'] },
  { source: 'p_tadeusz_zaborowski', target: 'biz_per', label: '', v: ['zespol'] },
  { source: 'p_adrian_szufel', target: 'biz_peg', label: '', v: ['zespol'] },
  { source: 'p_kamila_szczutkowska', target: 'biz_peg', label: '', v: ['zespol'] },
  { source: 'p_beata_kasprzak', target: 'biz_peo', label: '', v: ['zespol'] },
  { source: 'p_beata_kasprzak', target: 'biz_indu', label: '', v: ['zespol'] },
  { source: 'p_beata_kasprzak', target: 'biz_sunday', label: '', v: ['zespol'] },
  { source: 'p_viktoria_kulchytska_vouchko', target: 'biz_per', label: '', v: ['zespol'] },
  { source: 'p_viktoria_kulchytska_vouchko', target: 'biz_beachbox', label: '', v: ['zespol'] },
  { source: 'p_inna_kvasnikowa', target: 'biz_per', label: '', v: ['zespol'] },
  { source: 'p_inna_kvasnikowa', target: 'biz_beachbox', label: '', v: ['zespol'] },

];

// ==============================================================
// NODE META — rozszerzone opisy (opcjonalne)
// Pola: what / does[] / why / status / cost / owner / url
// Gdy brak — sidebar fallbackuje do node.desc
// Koszty w PLN/miesiąc, tylko liczby (atlas sumuje)
// ==============================================================
const nodeMeta = {
  // === APKI ===
  app_pm: {
    what: 'Pricing Manager — dashboard cen hotelowych obiektów PEO.',
    does: ['Scrapuje rynek Booking.com przez Apify (2 lokalizacje)', 'Liczy rekomendacje cen z kaskadą HIGH→MEDIUM→LOW', 'Generuje AI summary dziennych skanów (GPT-4o-mini)', 'Loguje każdy krok pipeline do BigQuery'],
    why: 'Pomaga ustalać ceny IND.U/Sunday/GEA. Dziś ręczne przepisanie do IdoBooking; docelowo auto-push po shadow mode.',
    status: '🟢 live',
    cost: 200,
    url: 'https://price.partnerexpert.work',
  },
  app_zakupex: {
    what: 'System faktur zakupowych PER z OCR.',
    does: ['Codziennie 02:00 pobiera faktury z maila', 'OCR przez GPT-4o', 'Reconciliation z wFirma', 'Wysyła raport mailem'],
    why: 'Automatyzuje księgowość PER — restauracje mają setki faktur miesięcznie.',
    status: '🟢 live (Cloud Run europe-west1)',
    cost: 3,
    url: 'https://zakupex.partnerexpert.work',
  },
  app_janusz: {
    what: 'PERSONA: WhatsApp bot wiedzy firmowej PEG.',
    does: ['Odpowiada na pytania zespołu z bazy Notion (Wiki/Biznesy/Umowy)', 'Moduł PM — recurring tasks per stanowisko', 'Timecard — karta pracy przez DM', 'Vision przy @Janusz + obrazek'],
    why: 'Odciąża Adiego z odpowiadania na podstawowe pytania, zbiera dane HR (godziny pracy).',
    status: '🟢 live',
    cost: 20,
  },
  app_gustaw: {
    what: 'PERSONA: WhatsApp asystent osobisty Adi.',
    does: ['Czeka na SIM', 'Docelowo: concierge — zadania, kalendarz, notatki'],
    why: 'Drugi filar persona — Janusz dla zespołu, Gustaw dla Adi.',
    status: '🔴 off (czeka na SIM)',
  },
  www_muszla: {
    what: 'muszlakolobrzeg.pl — strona Muszli Koncertowej.',
    does: ['Event listing', 'Rezerwacje', 'Afisz sezonowy'],
    why: 'Bookingi + marketing Muszli. Jedyna strona PEG która dostaje budżet Ads.',
    status: '🟢 live',
    url: 'https://muszlakolobrzeg.pl',
  },
  www_atlas: {
    what: 'Interaktywna mapa ekosystemu PEG.',
    does: ['3 widoki: Cortex / Biznesy / Zespół', 'Search, filtry, focus mode', 'Live status (w planach)'],
    why: 'Jednorazowe spojrzenie na całą infrastrukturę — co działa, co zjadacz kosztów.',
    status: '🟢 live',
    url: 'https://aszufel.github.io/atlas/',
  },

  // === INFRASTRUKTURA ===
  vercel: {
    what: 'Hosting Next.js apek PEG.',
    does: ['Auto-deploy z GitHub main', 'Serverless functions', 'Edge network', 'Preview deployments per PR'],
    why: 'Frontend + API dla PM + muszla.pl. (ZakupEX od 2026-04-13 na Cloud Run, BOT Voice skasowane 2026-04-18.)',
    status: '🟢 live',
    cost: 0,
    url: 'https://vercel.com/dashboard',
  },
  mikrus: {
    what: 'VPS 24/7 (leszek140) — hosting person i PG.',
    does: ['PM2 runtime dla Janusza (WA sesja persistent)', 'PostgreSQL Janusz DB (messages_log, timecard_entries)', 'archiwista cron 04:00 (backup PG + .env → strych)'],
    why: 'WhatsApp-web.js wymaga persistent sesji, Vercel/Cloud Run tego nie zrobią.',
    status: '🟢 live',
    cost: 20,
  },
  laptop: {
    what: 'Penguin — laptop Adi. Runtime Cortex interaktywny.',
    does: ['Claude Code sessions', 'Skrypty Cortex ad-hoc', 'systemd timers (7:00 context, 7:10 smoke, 22:00 claude-backup)'],
    why: 'Interaktywna praca. ZERO cronów produkcyjnych — te są w GCP.',
    status: '🟢 live',
  },
  dhosting: {
    what: 'Hosting statycznych stron PEG + email firmowy.',
    does: ['FTP deploy 4 stron HTML (IND.U, Sunday, GEA, PEG)', 'Skrzynki @partnerexpert.pl/.work'],
    why: 'Strony statyczne, email firmowy PEG.',
    status: '🟢 live',
  },

  // === GCP RESOURCES ===
  gcp: {
    what: 'Projekt ai-council-487609 — centralna infra Cortexu.',
    does: ['Cloud Functions + Cloud Run Jobs', 'Scheduler (15+ cronów)', 'Secret Manager (8 sekretów)', 'GCS bucket backups', 'BigQuery logs', 'Weather API dla PM'],
    why: 'Jeden projekt dla wszystkiego co jest serverside + automaty. Zastąpił crony na Mikrusie i dhosting.',
    status: '🟢 live',
    cost: 50,
    url: 'https://console.cloud.google.com/home/dashboard?project=ai-council-487609',
  },
  gcp_bq: {
    what: 'BigQuery cortex_logs.pipeline_logs — centralny dziennik PEG (4 app, ~15 sources). Lokalizacja: EU.',
    does: ['Zapis logów pipeline każdej apki', 'Partycje DAY, retention 30d', 'Query przez system_audit.py', 'Sekcja "Systemy w nocy" w briefingu', 'Cap 1000/dzień/source', 'PII filter w warstwie wrappera', 'Kolumny: created_at, app, level, source, event, message, meta (JSON), run_id'],
    why: 'Widoczność co się dzieje w nocy w apkach. Fundament pod auto-push cen PM, iteracyjne fixowanie błędów Janusza, monitoring backupów.',
    status: '🟢 live — 7 apek podłączonych (2026-04-20): cortex (recenzent/health-check/3×backup), janusz (vision/wa-connection/timecard), pm (webhook/generate-summary), zakupex (auto-import)',
    cost: 0,
  },
  gcp_sm: {
    what: 'Secret Manager — 8 sekretów PEG w jednym miejscu.',
    does: ['Notion tokens (2)', 'Supabase keys (PM, Zakupex)', 'OpenAI', 'Cloudflare', 'Cortex API key', 'Google OAuth'],
    why: 'Bezpieczny odczyt z Cloud Run/Functions, nie trzeba trzymać w kodzie.',
    status: '🟢 live',
  },
  gcp_bucket: {
    what: 'gs://peg-backups-cortex — backup storage.',
    does: ['Foldery: notion/, supabase/, cloudflare/, claude-config/, mikrus/, health-check/', 'Lifecycle 30 dni (auto-delete)'],
    why: 'Wszystkie backupy w jednym bucketcie, tanio, z retencją.',
    status: '🟢 live',
  },
  gcp_uptime: {
    what: 'Uptime Check — monitoring Janusza.',
    does: ['Ping /health Janusza co 5 min', 'Email alert po 60s downtime'],
    why: 'Janusz 24/7 — WA sesja musi żyć.',
    status: '🟢 live',
  },

  // === API / ZEWNĘTRZNE ===
  supabase: {
    what: 'Managed PostgreSQL + Auth dla apek.',
    does: ['DB PM (scans, properties, prices)', 'DB Zakupex (invoices, vendors)', 'Auth PM (magic link)', 'RLS na tabelach'],
    why: 'Jeden PG dla 2 apek, auth wbudowany, row-level security.',
    status: '🟢 live',
    cost: 0,
    url: 'https://supabase.com/dashboard/projects',
  },
  openai_api: {
    what: 'GPT-4o, GPT-4o-mini, Whisper.',
    does: ['PM: summary skanów (4o-mini)', 'Zakupex: OCR faktur (4o)', 'Janusz: Q&A + Vision (4o-mini)', 'Content pipeline: transkrypcja + pisanie (Whisper + 4o)', 'Cortex: fireflies, analiza journal'],
    why: 'Jedyny dostawca LLM/Vision/Whisper używany w PEG.',
    status: '🟢 live',
    cost: 50,
  },
  apify: {
    what: 'Actor marketplace — scraping.',
    does: ['PM: Fast Booking Scraper (2x dziennie × 2 lokalizacje)', 'Budżet: $50/mc, cykl 7-6'],
    why: 'Scraping Booking bez utrzymywania własnego playwright.',
    status: '🟢 live',
    cost: 200,
  },
  notion_api_firm: {
    what: 'Notion API — 20 baz firmowych PEG.',
    does: ['Zadania, Projekty, CRM, Aktywności, Pracownicy, Obowiązki, Biznesy, Umowy, Notatki, GUNB, Wiki'],
    why: 'Główne repozytorium wiedzy i operacji PEG. Używane przez Cortex i Janusz.',
    status: '🟢 live',
    cost: 80,
  },
  notion_api_priv: {
    what: 'Notion API — 12 baz prywatnych Adi.',
    does: ['Tasks, Goals, Habits, Notes, Dziennik Treningowy, Suplementy, Activity Log'],
    why: 'Życie osobiste — cele, nawyki, treningi, EOD. Nie mieszane z firmowymi.',
    status: '🟢 live',
  },
  cloudflare_api: {
    what: 'DNS + cache + analytics dla domen PEG.',
    does: ['10 domen PEG', 'Cache statycznych stron', 'SSL', 'Bot analytics'],
    why: 'Szybkie strony, darmowy SSL, ochrona przed botami.',
    status: '🟢 live',
    cost: 0,
  },

  // === CORTEX SCRIPTS (kluczowe) ===
  system_audit_py: {
    what: 'Skrypt audytu systemów — czyta BigQuery pipeline_logs.',
    does: ['summary [--last 24h] [--app <nazwa>]', 'errors — tylko błędy', 'tail — ostatnie N logów', 'run <run_id> — pełny cykl', 'briefing — skrót dla porannego briefingu'],
    why: 'Cortex rano wie co się działo w nocy w apkach, raportuje w "🤖 Systemy w nocy".',
    status: '🟢 live',
  },
  update_context_py: {
    what: 'Generator context.md — snapshot dnia.',
    does: ['Kalendarz (PEG + prywatny + rodzinny)', 'Zadania Notion', 'CRM aktywności', 'Habits', 'Inbox (2 konta)'],
    why: 'Briefing poranny czyta gotowy context.md zamiast 20 live queries.',
    status: '🟢 live',
  },
  seo_report_py: {
    what: 'Raport SEO dla stron PEG.',
    does: ['CF analytics + PSI + GSC + GA4', 'Wyjście: short (briefing pt) / notion (pełny raport) / JSON'],
    why: 'Piątkowy briefing: co z SEO stron PEG.',
    status: '🟢 live',
  },
  content_pipeline_py: {
    what: 'Pipeline rolek z podcastu Pana Tomka.',
    does: ['Download → transkrypcja Whisper', 'Wybór fragmentów przez GPT-4o', 'Cropy ffmpeg + OpenCV (face tracking 45%)', 'Napisy ASS karaoke-style', 'Upload do Drive Shared', 'Zapis do Notion Social Planner'],
    why: 'Persona Tamborski — automat FB content zasilający stronę w rolki tygodniowo.',
    status: '🟢 live',
    cost: 30,
  },

  // === SCHEDULER JOBS PM (krytyczne) ===
  sch_pm_scan: {
    what: 'Cron — PM auto-scan cen.',
    does: ['23:00 Warsaw → GET /api/cron/auto-scan', 'Trigger Apify na 2 lokalizacje'],
    why: 'Codzienny update cen rynku.',
    status: '🟢 live',
  },
  sch_pm_summary: {
    what: 'Cron — PM AI summary.',
    does: ['01:00 Warsaw → GET /api/cron/generate-summary', 'Summary dziennych skanów (GPT)'],
    why: 'Codzienne podsumowanie rynku nocne, rano w mailu.',
    status: '🟢 live',
  },
  sch_pm_retry: {
    what: 'Cron — PM retry Apify.',
    does: ['06:00 Warsaw → GET /api/cron/retry-apify-runs', 'Pasywny retry failed runs'],
    why: 'Jeśli webhook padł — rano dociągnięcie danych.',
    status: '🟢 live',
  },
  cr_health_check: {
    what: 'Cloud Function — health check apek PEG.',
    does: ['Ping 7 apek co 15 min', 'Alert WA (Janusz /send) przy UP↔DOWN', 'Throttle 60 min', '08:00 digest'],
    why: 'Instant alert gdy coś padnie w nocy.',
    status: '🟢 live',
  },

  // === BIZNESY — kluczowe ===
  biz_peg: {
    what: 'PEG to brand parasolowy — NIE formalny holding.',
    does: ['Wspólna nazwa handlowa dla PEI, PEO, PER', 'Ułatwia komunikację zewnętrzną', 'Wewnętrznie: 3 niezależne spółki'],
    why: 'Klienci widzą "Partner Expert GROUP" zamiast 3 osobnych firm. Prawnie każda spółka ma własny KRS, księgowość i zarząd.',
    status: '🏷️ brand (nie formalny podmiot)',
  },
  biz_pei: {
    what: 'Partner Expert Investments — spółka inwestycyjna.',
    does: ['Consulting dla deweloperów', 'Portfolio strategii (10 aktywnych)', 'Nabywanie lokalizacji'],
    why: 'Filar inwestycyjny PEG.',
    status: '🟢 aktywna',
  },
  biz_peo: {
    what: 'Partner Expert Operator — zarządzanie hotelami/apartamentami.',
    does: ['Operacje IND.U, Sunday, GEA, Wild Pearl', 'Pricing przez PM app', 'Check-in / Customer Service'],
    why: 'Filar operacyjny PEG — generuje 80% przychodów w sezonie.',
    status: '🟢 aktywna',
  },
  biz_per: {
    what: 'Partner Expert Restaurants — gastronomia.',
    does: ['Beach Box, Sunset Bar, Muszla Koncertowa', 'Zarządzanie sezonem gastro', 'Restrukturyzacja 2026'],
    why: 'Filar gastro PEG. Muszla to 7-letnia dzierżawa od miasta.',
    status: '🟡 restrukturyzacja',
  },

  // Cortex v2 migration (2026-04-18)
  cr_atlas_status: {
    what: 'Cloud Function — proxy bucketa health-check → atlas live status.',
    does: ['Czyta gs://peg-backups-cortex/health-check/state.json (SA auth)', 'Zwraca JSON z CORS', 'Atlas fetch co 60s → 🟢/🔴 per apka'],
    why: 'Atlas (statyczny HTML na GitHub Pages) nie może czytać prywatnego bucketa bezpośrednio — CF to proxy.',
    status: '🟢 live (2026-04-17)',
    cost: 0,
  },
  infra_snapshot_py: {
    what: 'Generator LIVE mapy infrastruktury Cortex/PEG.',
    does: ['gcloud scheduler/run/functions list (oba regiony)', 'ssh penguin pm2 jlist', 'systemctl --user list-timers + crontab -l', 'Zapis do knowledge/maps/_infra_live.md'],
    why: 'Single source of truth — koniec z rozjazdami ręcznych map vs rzeczywistości. Odpalany automatycznie przez update_context.py.',
    status: '🟢 live (2026-04-18)',
  },
  drift_linter_py: {
    what: 'Wykrywa rozjazdy między dokumentacją a rzeczywistością Cortex.',
    does: ['Skrypty w CLAUDE.md/knowledge/ istnieją w scripts/?', 'Memory references w MEMORY.md → pliki istnieją?', 'Zombie w mapach tekstowych vs LIVE?', 'Skills mają SKILL.md?', 'Stale docs >60 dni?', 'Home CLAUDE.md to symlink?'],
    why: 'Automatyczny strażnik spójności — wyłapuje drift zanim urośnie.',
    status: '🟢 live (2026-04-18)',
  },
  infra_live_md: {
    what: 'LIVE snapshot infry — auto-generowany markdown.',
    does: ['~100 linii: schedulery, Cloud Run services/jobs, Cloud Functions, Mikrus PM2, lokalne timery', 'Wklejany do context.md (każda sesja Claude ma aktualny stan)', 'Backup poprzedniej wersji w _infra_live.prev.md (diff-friendly)'],
    why: 'Jeden plik = jedna prawda. Claude nie zgaduje co istnieje w infrze.',
    status: '🟢 live (2026-04-18)',
  },
  cortex_routing_md: {
    what: 'Mapa "Adi mówi X → Claude robi Y".',
    does: ['Fraza naturalna → skrypt + parametry + domyślne zachowanie', 'Email (draft/send, PEG/prywatny), zadania, audyty WWW, GBP, health, Janusz, content pipeline', '13 nadrzędnych zasad (rób sam, max 2 próby, zakazane ops)'],
    why: 'Adi pisze naturalnie (polski, potocznie, bez hashtagów). Routing = moja robota rozpoznać intencję bez pytania.',
    status: '🟢 live (2026-04-18)',
  },
};
